import { zodResolver } from "@hookform/resolvers/zod";
import { Banknote, CalendarCheck, Clock3, LoaderCircle, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { createCashbookEntryInputSchema, dailyClosingInputSchema, type CreateCashbookEntryInput, type DailyClosingInput } from "@oil-agency/shared";
import { ApiError, apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { useAuthStore } from "@/stores/auth-store";

const pakistanDateParts = Object.fromEntries(new Intl.DateTimeFormat("en", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()).map((part) => [part.type, part.value]));
const today = `${pakistanDateParts.year}-${pakistanDateParts.month}-${pakistanDateParts.day}`;
type UserOption = { id: string; displayName: string; username: string };
type CashEntry = { id: string; entryNumber: string; entryType: string; direction: "IN" | "OUT"; amount: string; runningBalance: string; occurredAt: string; reference: string | null; notes: string | null; createdBy: UserOption; transactionReference: { type: string; number: string; documentNumber: string | null; party: string | null } | null };
type Closing = { id: string; businessDate: string; openingCash: string; cashIn: string; cashOut: string; expectedCash: string; countedCash: string; difference: string; notes: string | null; closedAt: string; closedBy: UserOption };
type Report = { entries: CashEntry[]; summary: { openingCash: string; cashIn: string; cashOut: string; expectedCash: string }; closings: Closing[] };
type Day = { businessDate: string; openingCash: string; cashIn: string; cashOut: string; expectedCash: string; closed: boolean; closing: { countedCash: string; difference: string; closedBy: { displayName: string } } | null };
const entryDefaults: CreateCashbookEntryInput = { entryType: "OPENING_CASH", direction: "IN", amount: "0.00", occurredOn: today, reference: "", notes: "" };
const closeDefaults: DailyClosingInput = { businessDate: today, countedCash: "0.00", notes: "" };
const directions: Partial<Record<CreateCashbookEntryInput["entryType"], "IN" | "OUT">> = { OPENING_CASH: "IN", CASH_DEPOSIT: "OUT", CASH_WITHDRAWAL: "IN", OWNER_INVESTMENT: "IN", OWNER_WITHDRAWAL: "OUT", OTHER_INCOME: "IN", OTHER_EXPENSE: "OUT" };
const labels: Array<[CreateCashbookEntryInput["entryType"], string]> = [["OPENING_CASH", "Opening cash"], ["CASH_DEPOSIT", "Cash deposit"], ["CASH_WITHDRAWAL", "Cash withdrawal"], ["OWNER_INVESTMENT", "Owner investment"], ["OWNER_WITHDRAWAL", "Owner withdrawal"], ["OTHER_INCOME", "Other income"], ["OTHER_EXPENSE", "Other expense"], ["CLOSING_ADJUSTMENT", "Closing adjustment"]];

export function CashbookPage() {
  const token = useAuthStore((state) => state.token)!; const [from, setFrom] = useState(today); const [to, setTo] = useState(today); const [userId, setUserId] = useState(""); const [users, setUsers] = useState<UserOption[]>([]); const [report, setReport] = useState<Report | null>(null); const [day, setDay] = useState<Day | null>(null); const [message, setMessage] = useState("");
  const entryForm = useForm<CreateCashbookEntryInput>({ resolver: zodResolver(createCashbookEntryInputSchema), defaultValues: entryDefaults }); const closingForm = useForm<DailyClosingInput>({ resolver: zodResolver(dailyClosingInputSchema), defaultValues: closeDefaults }); const closeDate = closingForm.watch("businessDate");
  async function loadReport() { try { const query = new URLSearchParams({ from, to, ...(userId ? { userId } : {}) }); const data = await apiRequest<Report>(`/cashbook/report?${query}`, {}, token); setReport(data); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load cashbook."); } }
  async function loadDay(date: string) { try { setDay(await apiRequest<Day>(`/cashbook/day/${date}`, {}, token)); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not calculate daily cash."); } }
  useEffect(() => { void apiRequest<{ users: UserOption[] }>("/cashbook/users", {}, token).then((value) => setUsers(value.users)); }, [token]); useEffect(() => { void loadReport(); }, [from, to, userId, token]); useEffect(() => { if (closeDate) void loadDay(closeDate); }, [closeDate, token]);
  async function createEntry(input: CreateCashbookEntryInput) { setMessage(""); try { await apiRequest("/cashbook/entries", { method: "POST", body: JSON.stringify(input) }, token); setMessage("Cashbook entry posted successfully."); entryForm.reset({ ...entryDefaults, occurredOn: input.occurredOn }); await Promise.all([loadReport(), loadDay(closeDate)]); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Cash entry could not be posted."); } }
  async function closeDay(input: DailyClosingInput) { setMessage(""); try { await apiRequest("/cashbook/closings", { method: "POST", body: JSON.stringify(input) }, token); setMessage(`${input.businessDate} closed successfully.`); await Promise.all([loadReport(), loadDay(input.businessDate)]); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Daily closing failed."); } }
  return <section className="p-8"><div className="mb-6"><p className="mb-1 text-sm font-semibold text-primary">Cash control</p><h1 className="m-0 text-3xl font-bold">Cashbook & daily closing</h1><p className="mt-2 text-sm text-muted-foreground">Cashiers cannot access this screen. Every manual entry and daily close is audit logged.</p><div className="mt-3 flex w-fit items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-900"><Clock3 size={15}/>Automatic closing runs daily at 8:00 PM Pakistan time (Asia/Karachi). System expected cash is recorded as counted cash; use manual closing before 8:00 PM when a physical cash count is required.</div></div>{message && <div className="mb-5 rounded-lg border bg-slate-50 p-3 text-sm">{message}</div>}
    <Card className="mb-5 p-5"><div className="grid grid-cols-[200px_200px_260px_1fr] items-end gap-3"><label className="text-sm font-medium">From<Input className="mt-1" type="date" value={from} onChange={(event) => setFrom(event.target.value)}/></label><label className="text-sm font-medium">To<Input className="mt-1" type="date" value={to} onChange={(event) => setTo(event.target.value)}/></label><label className="text-sm font-medium">User<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" value={userId} onChange={(event) => setUserId(event.target.value)}><option value="">All users</option>{users.map((user) => <option key={user.id} value={user.id}>{user.displayName}</option>)}</select></label><div className="text-right text-xs text-muted-foreground">Pakistan business day (UTC+05:00)</div></div></Card>
    <div className="mb-5 grid grid-cols-4 gap-4"><Summary title="Opening cash" value={report?.summary.openingCash}/><Summary title="Cash in" value={report?.summary.cashIn} tone="green"/><Summary title="Cash out" value={report?.summary.cashOut} tone="red"/><Summary title="Expected cash" value={report?.summary.expectedCash} strong/></div>
    <div className="mb-5 grid grid-cols-2 gap-5"><Card className="p-5"><div className="mb-4 flex items-center gap-2"><Plus size={19}/><h2 className="m-0 text-lg">Post cash entry</h2></div><form className="grid grid-cols-2 gap-3" onSubmit={entryForm.handleSubmit(createEntry)}><label className="text-sm font-medium">Entry type<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" {...entryForm.register("entryType")} onChange={(event) => { const type = event.target.value as CreateCashbookEntryInput["entryType"]; entryForm.setValue("entryType", type); if (directions[type]) entryForm.setValue("direction", directions[type]!); }} >{labels.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-medium">Direction<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" {...entryForm.register("direction")}><option value="IN">Cash in</option><option value="OUT">Cash out</option></select></label><label className="text-sm font-medium">Amount<Input className="mt-1" {...entryForm.register("amount")}/></label><label className="text-sm font-medium">Business date<Input className="mt-1" type="date" {...entryForm.register("occurredOn")}/></label><label className="col-span-2 text-sm font-medium">Reference<Input className="mt-1" {...entryForm.register("reference")} placeholder="Voucher, deposit slip, or other reference"/></label><label className="col-span-2 text-sm font-medium">Reason / notes<Textarea className="mt-1" rows={3} {...entryForm.register("notes")}/></label><div className="col-span-2 flex justify-end"><Button disabled={entryForm.formState.isSubmitting}>{entryForm.formState.isSubmitting && <LoaderCircle className="mr-2 animate-spin" size={17}/>}Post entry</Button></div></form></Card>
      <Card className="p-5"><div className="mb-4 flex items-center gap-2"><CalendarCheck size={19}/><h2 className="m-0 text-lg">Daily closing</h2></div><div className="mb-4 grid grid-cols-2 gap-2 rounded-lg bg-slate-50 p-4 text-sm"><span>Opening cash</span><strong className="text-right">PKR {day?.openingCash ?? "0.00"}</strong><span>Cash in</span><strong className="text-right text-emerald-700">PKR {day?.cashIn ?? "0.00"}</strong><span>Cash out</span><strong className="text-right text-red-700">PKR {day?.cashOut ?? "0.00"}</strong><span className="border-t pt-2 font-semibold">Expected cash</span><strong className="border-t pt-2 text-right">PKR {day?.expectedCash ?? "0.00"}</strong></div>{day?.closed ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><strong>Day already closed</strong><p className="mb-0 mt-2 text-sm">Actual: PKR {day.closing?.countedCash} · Difference: PKR {day.closing?.difference}<br/>Closed by {day.closing?.closedBy.displayName}</p></div> : <form className="grid grid-cols-2 gap-3" onSubmit={closingForm.handleSubmit(closeDay)}><label className="text-sm font-medium">Business date<Input className="mt-1" type="date" {...closingForm.register("businessDate")}/></label><label className="text-sm font-medium">Actual counted cash<Input className="mt-1" {...closingForm.register("countedCash")}/></label><label className="col-span-2 text-sm font-medium">Closing notes<Textarea className="mt-1" rows={3} {...closingForm.register("notes")}/></label><div className="col-span-2 flex justify-end"><Button disabled={closingForm.formState.isSubmitting}>{closingForm.formState.isSubmitting && <LoaderCircle className="mr-2 animate-spin" size={17}/>}Close business day</Button></div></form>}</Card></div>
    <Card className="mb-5"><div className="p-5 pb-2"><h2 className="m-0 text-lg">Cashbook report</h2></div><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Entry</TableHead><TableHead>Reference transaction</TableHead><TableHead>User</TableHead><TableHead>Cash in</TableHead><TableHead>Cash out</TableHead><TableHead>Running</TableHead></TableRow></TableHeader><TableBody>{report?.entries.length ? report.entries.map((entry) => <TableRow key={entry.id}><TableCell>{new Date(entry.occurredAt).toLocaleDateString()}</TableCell><TableCell><strong>{entry.entryType.replaceAll("_", " ")}</strong><span className="block text-xs text-muted-foreground">{entry.notes}</span></TableCell><TableCell>{entry.transactionReference ? <><strong>{entry.transactionReference.number}</strong><span className="block text-xs text-muted-foreground">{entry.transactionReference.documentNumber ?? entry.transactionReference.party}</span></> : entry.reference ?? "—"}</TableCell><TableCell>{entry.createdBy.displayName}</TableCell><TableCell className="text-emerald-700">{entry.direction === "IN" ? `PKR ${entry.amount}` : "—"}</TableCell><TableCell className="text-red-700">{entry.direction === "OUT" ? `PKR ${entry.amount}` : "—"}</TableCell><TableCell className="font-semibold">PKR {entry.runningBalance}</TableCell></TableRow>) : <TableRow><TableCell colSpan={7} className="py-10 text-center text-muted-foreground">No cash entries in this period.</TableCell></TableRow>}</TableBody></Table></Card>
    <Card><div className="p-5 pb-2"><h2 className="m-0 text-lg">Daily closing report</h2></div><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Opening</TableHead><TableHead>Cash in</TableHead><TableHead>Cash out</TableHead><TableHead>Expected</TableHead><TableHead>Actual</TableHead><TableHead>Difference</TableHead><TableHead>Closed by</TableHead></TableRow></TableHeader><TableBody>{report?.closings.length ? report.closings.map((closing) => <TableRow key={closing.id}><TableCell>{closing.businessDate}</TableCell><TableCell>PKR {closing.openingCash}</TableCell><TableCell>PKR {closing.cashIn}</TableCell><TableCell>PKR {closing.cashOut}</TableCell><TableCell>PKR {closing.expectedCash}</TableCell><TableCell>PKR {closing.countedCash}</TableCell><TableCell className={Number(closing.difference) === 0 ? "" : Number(closing.difference) < 0 ? "text-red-700 font-semibold" : "text-amber-700 font-semibold"}>PKR {closing.difference}</TableCell><TableCell>{closing.closedBy.displayName}</TableCell></TableRow>) : <TableRow><TableCell colSpan={8} className="py-8 text-center text-muted-foreground">No daily closings in this period.</TableCell></TableRow>}</TableBody></Table></Card>
  </section>;
}
function Summary({ title, value = "0.00", tone, strong = false }: { title: string; value?: string | undefined; tone?: "green" | "red"; strong?: boolean }) { return <Card className="p-5"><div className="flex items-center justify-between"><div><p className="m-0 text-sm text-muted-foreground">{title}</p><p className={`mb-0 mt-2 text-2xl font-bold ${tone === "green" ? "text-emerald-700" : tone === "red" ? "text-red-700" : ""}`}>PKR {value}</p></div>{strong && <Banknote className="text-primary"/>}</div></Card>; }
