import { AlertTriangle, ArchiveX, Boxes, CalendarClock, ClipboardList, DatabaseBackup, LoaderCircle, PackageSearch, ReceiptText, RefreshCw, Truck, Users } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useAuthStore } from "@/stores/auth-store";

type Dashboard = { businessDate: string; cards: { todayInvoiceCount: number; lowStockProducts: number; nearExpiryProducts: number; expiredProducts: number; damagedAlerts: number; pendingCustomerPayments: number; pendingSupplierPayments: number }; lowStock: Array<{ id: string; name: string; sku: string; availableBaseQty: number; reorderLevelBaseQty: number; baseUnit: string }>; expiryAlerts: Array<{ productId: string; product: string; sku: string; batchNumber: string; expiryDate: string; stockBaseQty: number; status: "EXPIRED" | "NEAR_EXPIRY" }>; damageAlerts: Array<{ id: string; entryNumber: string; quantityBase: number; reason: string; occurredAt: string; product: { name: string; sku: string; baseUnit: { symbol: string } }; batch: { batchNumber: string } | null }>; pendingCustomers: Array<{ id: string; code: string; name: string; businessName: string | null; phone: string | null; outstanding: string }>; pendingSuppliers: Array<{ id: string; code: string; name: string; businessName: string | null; phone: string | null; outstanding: string }>; recentSales: Array<{ id: string; invoiceNumber: string; soldAt: string; paymentStatus: string; customer: { name: string; businessName: string | null } | null; createdBy: { displayName: string } }>; recentPurchases: Array<{ id: string; invoiceNumber: string; supplierInvoice: string | null; purchasedAt: string; paymentStatus: string; supplier: { name: string; businessName: string | null }; createdBy: { displayName: string } }>; backup: { status: "COMPLETED" | "NEVER"; createdAt: string | null; createdBy: string | null } };

export function HomePage() { const navigate = useNavigate(); const token = useAuthStore((state) => state.token)!; const user = useAuthStore((state) => state.user)!; const [data, setData] = useState<Dashboard | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); async function load() { setLoading(true); setMessage(""); try { setData(await apiRequest<Dashboard>("/dashboard", {}, token)); } catch (error) { setMessage(error instanceof Error ? error.message : "Dashboard could not be loaded."); } finally { setLoading(false); } } useEffect(() => { void load(); }, [token]);
  if (loading && !data) return <div className="grid h-full place-items-center"><LoaderCircle className="animate-spin text-primary"/></div>;
  return <section className="min-h-full p-5"><div className="mb-4 flex h-12 items-center justify-between"><div><p className="m-0 text-xs font-semibold uppercase tracking-wide text-primary">Operational dashboard · {data?.businessDate}</p><h1 className="m-0 mt-1 text-2xl font-bold">Assalam-o-Alaikum, {user.displayName}</h1></div><Button size="sm" variant="outline" onClick={() => void load()} disabled={loading}>{loading ? <LoaderCircle className="mr-2 animate-spin" size={15}/> : <RefreshCw className="mr-2" size={15}/>}Refresh</Button></div>{message && <div className="mb-3 rounded-lg border bg-white p-2 text-xs">{message}</div>}
    <div className="mb-4 grid grid-cols-7 gap-2.5"><Metric icon={<ReceiptText/>} label="Today's invoices" value={data?.cards.todayInvoiceCount ?? 0}/><Metric icon={<Boxes/>} label="Low stock" value={data?.cards.lowStockProducts ?? 0} tone="amber"/><Metric icon={<CalendarClock/>} label="Near expiry" value={data?.cards.nearExpiryProducts ?? 0} tone="amber"/><Metric icon={<ArchiveX/>} label="Expired" value={data?.cards.expiredProducts ?? 0} tone="red"/><Metric icon={<AlertTriangle/>} label="Damaged alerts" value={data?.cards.damagedAlerts ?? 0} tone="red"/><Metric icon={<Users/>} label="Customer dues" value={data?.cards.pendingCustomerPayments ?? 0}/><Metric icon={<Truck/>} label="Supplier dues" value={data?.cards.pendingSupplierPayments ?? 0}/></div>
    <div className="grid grid-cols-3 gap-3"><Card className="h-[520px] overflow-hidden p-4"><Title icon={<PackageSearch/>}>Stock alerts</Title><Subheading>Low stock</Subheading><div className="space-y-0.5">{data?.lowStock.slice(0, 4).map((row) => <CompactRow key={row.id} title={row.name} note={`${row.sku} · reorder ${row.reorderLevelBaseQty}`} value={`${row.availableBaseQty} ${row.baseUnit}`}/>) ?? null}{!data?.lowStock.length && <Empty/>}</div><Subheading>Expiry</Subheading><div className="space-y-0.5">{data?.expiryAlerts.slice(0, 4).map((row) => <CompactRow key={`${row.productId}-${row.batchNumber}`} title={row.product} note={`${row.batchNumber} · ${new Date(row.expiryDate).toLocaleDateString()}`} value={row.status === "EXPIRED" ? "Expired" : "Near"} danger={row.status === "EXPIRED"}/>) ?? null}{!data?.expiryAlerts.length && <Empty/>}</div><Subheading>Recent damage</Subheading>{data?.damageAlerts.slice(0, 2).map((row) => <CompactRow key={row.id} title={row.product.name} note={row.reason} value={`${row.quantityBase} ${row.product.baseUnit.symbol}`} danger/>) ?? null}{!data?.damageAlerts.length && <Empty/>}</Card>
      <Card className="h-[520px] overflow-hidden p-4"><Title icon={<Users/>}>Pending payments</Title><Subheading>Customers</Subheading><div className="space-y-0.5">{data?.pendingCustomers.slice(0, 5).map((row) => <CompactRow key={row.id} title={row.businessName ?? row.name} note={`${row.code}${row.phone ? ` · ${row.phone}` : ""}`} value={`PKR ${row.outstanding}`}/>) ?? null}{!data?.pendingCustomers.length && <Empty/>}</div><Subheading>Suppliers</Subheading><div className="space-y-0.5">{data?.pendingSuppliers.slice(0, 5).map((row) => <CompactRow key={row.id} title={row.businessName ?? row.name} note={`${row.code}${row.phone ? ` · ${row.phone}` : ""}`} value={`PKR ${row.outstanding}`}/>) ?? null}{!data?.pendingSuppliers.length && <Empty/>}</div></Card>
      <Card className="h-[520px] overflow-hidden p-4"><Title icon={<ClipboardList/>}>Recent activity</Title><Subheading>Sales</Subheading><div className="space-y-0.5">{data?.recentSales.slice(0, 4).map((row) => <CompactRow key={row.id} title={row.invoiceNumber} note={`${row.customer?.businessName ?? row.customer?.name ?? "Walk-in"} · ${new Date(row.soldAt).toLocaleString([], { dateStyle: "short", timeStyle: "short" })}`} value={row.paymentStatus} onClick={() => navigate(`/sales/${row.id}`)}/>) ?? null}{!data?.recentSales.length && <Empty/>}</div><Subheading>Purchases</Subheading><div className="space-y-0.5">{data?.recentPurchases.slice(0, 4).map((row) => <CompactRow key={row.id} title={row.invoiceNumber} note={`${row.supplier.businessName ?? row.supplier.name} · ${new Date(row.purchasedAt).toLocaleDateString()}`} value={row.paymentStatus}/>) ?? null}{!data?.recentPurchases.length && <Empty/>}</div><div className="mt-3 flex items-center gap-3 rounded-lg bg-slate-50 p-3"><DatabaseBackup size={18} className={data?.backup.status === "COMPLETED" ? "text-emerald-700" : "text-amber-700"}/><div className="min-w-0 flex-1"><p className="m-0 text-xs font-semibold">Last backup</p><p className="m-0 mt-0.5 truncate text-[11px] text-muted-foreground">{data?.backup.createdAt ? `${new Date(data.backup.createdAt).toLocaleString()} · ${data.backup.createdBy}` : "No completed backup recorded"}</p></div><span className="text-[10px] font-bold">{data?.backup.status}</span></div></Card></div>
  </section>; }
function Metric({ icon, label, value, tone }: { icon: ReactNode; label: string; value: number; tone?: "amber" | "red" }) { return <Card className="flex h-[74px] items-center gap-2.5 p-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg [&>svg]:h-4 [&>svg]:w-4 ${tone === "red" ? "bg-red-50 text-red-700" : tone === "amber" ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-primary"}`}>{icon}</span><div className="min-w-0"><p className="m-0 truncate text-[11px] text-muted-foreground">{label}</p><p className="m-0 text-xl font-bold leading-6">{value}</p></div></Card>; }
function Title({ icon, children }: { icon: ReactNode; children: ReactNode }) { return <div className="mb-2 flex items-center gap-2 text-sm font-bold"><span className="text-primary [&>svg]:h-4 [&>svg]:w-4">{icon}</span>{children}</div>; }
function Subheading({ children }: { children: ReactNode }) { return <p className="mb-1 mt-3 border-b pb-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{children}</p>; }
function CompactRow({ title, note, value, danger = false, onClick }: { title: string; note: string; value: string; danger?: boolean; onClick?: () => void }) { return <button type="button" disabled={!onClick} onClick={onClick} className="flex h-9 w-full items-center gap-2 rounded px-1.5 text-left hover:bg-slate-50 disabled:cursor-default disabled:hover:bg-transparent"><div className="min-w-0 flex-1"><p className="m-0 truncate text-xs font-semibold">{title}</p><p className="m-0 truncate text-[10px] text-muted-foreground">{note}</p></div><span className={`shrink-0 text-[10px] font-bold ${danger ? "text-red-700" : "text-foreground"}`}>{value.replaceAll("_", " ")}</span></button>; }
function Empty() { return <p className="m-0 py-2 text-center text-[11px] text-muted-foreground">No alerts</p>; }
