import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { INVENTORY_MOVEMENT_TYPES } from "@oil-agency/shared";
import { apiRequest } from "@/api/client";
import { Card } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useAuthStore } from "@/stores/auth-store";

type Movement={id:string;movementType:string;quantityBase:number;balanceAfterBase:number;notes:string|null;createdAt:string;product:{name:string;sku:string};batch:{batchNumber:string}|null;createdBy:{displayName:string;username:string}};
export function InventoryMovementsPage(){const token=useAuthStore(s=>s.token)!;const [searchParams]=useSearchParams();const productId=searchParams.get("productId")??"";const [items,setItems]=useState<Movement[]>([]);const [type,setType]=useState("");const [error,setError]=useState("");useEffect(()=>{const query=new URLSearchParams();if(type)query.set("type",type);if(productId)query.set("productId",productId);const q=query.size?`?${query}`:"";void apiRequest<{movements:Movement[]}>(`/inventory/movements${q}`,{},token).then(r=>{setItems(r.movements);setError("")}).catch((e:Error)=>setError(e.message))},[productId,token,type]);return <section className="p-8"><div className="mb-7"><p className="mb-2 text-sm font-semibold text-primary">PRODUCT STOCK</p><h1 className="m-0 text-3xl font-bold">Stock movement history</h1><p className="mt-2 text-sm text-muted-foreground">An immutable record of every stock change, including the user responsible.</p></div>{error&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</div>}<Card className="mb-5 p-4"><select className="h-11 min-w-64 rounded-lg border bg-white px-3" value={type} onChange={e=>setType(e.target.value)}><option value="">All movement types</option>{INVENTORY_MOVEMENT_TYPES.map(t=><option key={t}>{t}</option>)}</select>{productId&&<span className="ml-3 text-sm text-muted-foreground">Filtered to the selected product</span>}</Card><Card><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Product / batch</TableHead><TableHead>Type</TableHead><TableHead>Change</TableHead><TableHead>Balance</TableHead><TableHead>User</TableHead><TableHead>Notes</TableHead></TableRow></TableHeader><TableBody>{items.map(m=><TableRow key={m.id}><TableCell>{new Date(m.createdAt).toLocaleString()}</TableCell><TableCell><strong>{m.product.name}</strong><span className="block text-xs text-muted-foreground">{m.product.sku}{m.batch?` · ${m.batch.batchNumber}`:""}</span></TableCell><TableCell>{m.movementType}</TableCell><TableCell className={m.quantityBase<0?"text-red-700":"text-emerald-700"}>{m.quantityBase>0?"+":""}{m.quantityBase}</TableCell><TableCell>{m.balanceAfterBase}</TableCell><TableCell>{m.createdBy.displayName}</TableCell><TableCell>{m.notes??"—"}</TableCell></TableRow>)}</TableBody></Table></Card></section>}
