import { useEffect, useState } from "react";
import { RotateCcw } from "lucide-react";
import { apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAuthStore } from "@/stores/auth-store";

type Purchase = { id: string; invoiceNumber: string; supplierInvoice: string | null; supplier: { name: string }; total: string };
type Original = { id: string; invoiceNumber: string; supplier: { name: string }; items: Array<{ id: string; productName: string; sku: string; batchNumber: string | null; remainingQuantityBase: number; baseUnit: string; unitCost: string }> };
const today = () => new Date().toISOString().slice(0, 10);

export function PurchaseReturnsPage() {
  const token = useAuthStore((state) => state.token)!;
  const [purchases, setPurchases] = useState<Purchase[]>([]), [purchaseId, setPurchaseId] = useState(""), [original, setOriginal] = useState<Original | null>(null), [quantities, setQuantities] = useState<Record<string, number>>({});
  const [method, setMethod] = useState("SUPPLIER_LEDGER"), [reason, setReason] = useState(""), [returnedOn, setReturnedOn] = useState(today()), [message, setMessage] = useState("");
  useEffect(() => { void apiRequest<{ purchases: Purchase[] }>("/purchases?page=1&pageSize=100", {}, token).then((value) => setPurchases(value.purchases)); }, []);
  useEffect(() => { if (!purchaseId) { setOriginal(null); return; } void apiRequest<Original>(`/purchase-returns/purchase/${purchaseId}`, {}, token).then(setOriginal).catch((error) => setMessage(error.message)); }, [purchaseId]);
  const submit = async () => { const items = Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([purchaseItemId, quantityBase]) => ({ purchaseItemId, quantityBase })); if (!items.length) return setMessage("Enter a return quantity for at least one item."); try { const result = await apiRequest<{ returnNumber: string }>("/purchase-returns", { method: "POST", body: JSON.stringify({ purchaseId, returnedOn, method, reason, items }) }, token); setMessage(`Purchase return ${result.returnNumber} posted successfully.`); setQuantities({}); setOriginal(await apiRequest(`/purchase-returns/purchase/${purchaseId}`, {}, token)); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not post purchase return."); } };
  return <div className="mx-auto max-w-6xl space-y-5 p-6"><header><p className="mb-1 text-xs font-bold uppercase tracking-[.18em] text-primary">Purchases</p><h1 className="m-0 text-3xl font-bold">Purchase returns</h1><p className="mt-1 text-sm text-muted-foreground">Return goods against the original supplier invoice without deleting financial records.</p></header>{message && <div className="rounded-2xl border bg-white px-4 py-3 text-sm">{message}</div>}<Card className="grid gap-3 rounded-2xl p-5 md:grid-cols-3"><label className="space-y-1 md:col-span-2"><span className="text-sm font-medium">Original purchase</span><select className="h-11 w-full rounded-xl border bg-white px-3" value={purchaseId} onChange={(e) => setPurchaseId(e.target.value)}><option value="">Select supplier invoice</option>{purchases.map((purchase) => <option key={purchase.id} value={purchase.id}>{purchase.invoiceNumber} · {purchase.supplier.name} · {purchase.supplierInvoice ?? "No supplier reference"}</option>)}</select></label><label className="space-y-1"><span className="text-sm font-medium">Return date</span><Input type="date" value={returnedOn} onChange={(e) => setReturnedOn(e.target.value)}/></label></Card>{original && <><Card className="overflow-hidden rounded-2xl"><div className="border-b p-4"><strong>{original.invoiceNumber}</strong><span className="ml-3 text-sm text-muted-foreground">{original.supplier.name}</span></div><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-left text-xs uppercase text-slate-500"><th className="p-4">Product</th><th>Batch</th><th>Available to return</th><th className="p-4">Return quantity</th></tr></thead><tbody>{original.items.map((item) => <tr key={item.id} className="border-t"><td className="p-4"><strong>{item.productName}</strong><small className="block text-muted-foreground">{item.sku}</small></td><td>{item.batchNumber ?? "General"}</td><td>{item.remainingQuantityBase} {item.baseUnit}</td><td className="p-4"><Input className="max-w-36" type="number" min="0" max={item.remainingQuantityBase} value={quantities[item.id] ?? 0} onChange={(e) => setQuantities({...quantities,[item.id]:Math.min(item.remainingQuantityBase,Math.max(0,Number(e.target.value)))})}/></td></tr>)}</tbody></table></Card><Card className="grid gap-3 rounded-2xl p-5 md:grid-cols-[220px_1fr_auto]"><select className="h-11 rounded-xl border bg-white px-3" value={method} onChange={(e) => setMethod(e.target.value)}><option value="SUPPLIER_LEDGER">Adjust supplier ledger</option><option value="CASH">Cash refund received</option></select><Input placeholder="Reason for return" value={reason} onChange={(e) => setReason(e.target.value)}/><Button className="gap-2 rounded-xl" disabled={reason.trim().length < 3} onClick={() => void submit()}><RotateCcw size={16}/>Post return</Button></Card></>}</div>;
}
