import { BarChart3, Download, FileText, LoaderCircle, Printer, RefreshCw } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { exportReportCsv, exportReportPdf, printReport, type ReportCell, type ReportSection } from "@/features/reports/export-helpers";
import { useAuthStore } from "@/stores/auth-store";

const today = new Date().toLocaleDateString("en-CA"); const monthStart = `${today.slice(0, 8)}01`;
type Option = { id: string; name: string; businessName?: string | null; sku?: string; categoryId?: string | null };
type Options = { customers: Option[]; suppliers: Option[]; products: Option[]; categories: Option[] };
type Kind = "SALES" | "INVENTORY" | "WRITE_OFFS" | "CUSTOMER_LEDGER" | "PURCHASES" | "SUPPLIER_LEDGER" | "EXPENSES" | "CASHBOOK";
const kinds: Array<{ value: Kind; label: string; owner?: boolean }> = [{ value: "SALES", label: "Sales" }, { value: "INVENTORY", label: "Stock, batches & expiry" }, { value: "WRITE_OFFS", label: "Expired & damaged stock" }, { value: "CUSTOMER_LEDGER", label: "Customer ledger & receivables" }, { value: "PURCHASES", label: "Purchases", owner: true }, { value: "SUPPLIER_LEDGER", label: "Supplier ledger & payables", owner: true }, { value: "EXPENSES", label: "Expenses", owner: true }, { value: "CASHBOOK", label: "Cashbook", owner: true }];
const endpoint: Record<Kind, string> = { SALES: "sales", INVENTORY: "inventory", WRITE_OFFS: "write-offs", CUSTOMER_LEDGER: "customer-ledgers", PURCHASES: "purchases", SUPPLIER_LEDGER: "supplier-ledgers", EXPENSES: "expenses", CASHBOOK: "cashbook" };
const record = (value: unknown) => value as Record<string, unknown>; const rows = (value: unknown, key: string) => (record(value)[key] as Array<Record<string, unknown>> | undefined) ?? [];
const cell = (value: unknown): ReportCell => typeof value === "string" || typeof value === "number" || typeof value === "boolean" || value == null ? value as ReportCell : JSON.stringify(value);
const mapped = (values: Array<Record<string, unknown>>, transform: (row: Record<string, unknown>) => Record<string, ReportCell>) => values.map(transform);
const cols = (...values: Array<[string, string]>) => values.map(([key, label]) => ({ key, label }));

function shape(kind: Kind, data: unknown): { summary: Record<string, ReportCell>; sections: ReportSection[] } {
  const root = record(data); const summary = Object.fromEntries(Object.entries(record(root.summary ?? {})).filter(([key]) => !key.endsWith("Minor")).map(([key, value]) => [label(key), cell(value)]));
  if (kind === "SALES") return { summary, sections: [
    { title: "Invoice detail", columns: cols(["date", "Date"], ["invoiceNumber", "Invoice"], ["customer", "Customer"], ["settlement", "Cash / credit"], ["paymentMethods", "Payment"], ["quantityBase", "Qty"], ["sales", "Sales (PKR)"], ["paid", "Paid (PKR)"]), rows: mapped(rows(data, "invoices"), primitive) },
    { title: "Daily sales", columns: cols(["date", "Date"], ["invoiceCount", "Invoices"], ["quantityBase", "Quantity"], ["sales", "Sales (PKR)"]), rows: mapped(rows(data, "daily"), primitive) },
    { title: "Product-wise sales", columns: cols(["name", "Product"], ["sku", "SKU"], ["category", "Category"], ["invoiceCount", "Invoices"], ["quantityBase", "Quantity"], ["sales", "Sales (PKR)"]), rows: mapped(rows(data, "products"), primitive) },
    { title: "Customer-wise sales", columns: cols(["name", "Customer"], ["invoiceCount", "Invoices"], ["sales", "Sales (PKR)"]), rows: mapped(rows(data, "customers"), primitive) },
    { title: "Cash and credit sales", columns: cols(["type", "Settlement"], ["invoiceCount", "Invoices"], ["sales", "Sales (PKR)"]), rows: mapped(rows(data, "settlements"), primitive) },
  ] };
  if (kind === "PURCHASES") return { summary, sections: [{ title: "Purchase detail", columns: cols(["date", "Date"], ["invoiceNumber", "Purchase"], ["supplierInvoice", "Supplier invoice"], ["supplier", "Supplier"], ["paymentStatus", "Status"], ["paymentMethods", "Payment"], ["purchases", "Purchases (PKR)"], ["paid", "Paid (PKR)"]), rows: mapped(rows(data, "rows"), primitive) }, { title: "Daily purchases", columns: cols(["date", "Date"], ["invoiceCount", "Invoices"], ["purchases", "Purchases (PKR)"]), rows: mapped(rows(data, "daily"), primitive) }, { title: "Supplier-wise purchases", columns: cols(["name", "Supplier"], ["invoiceCount", "Invoices"], ["purchases", "Purchases (PKR)"]), rows: mapped(rows(data, "suppliers"), primitive) }] };
  if (kind === "INVENTORY") return { summary: { "Current products": rows(data, "current").length, "Low-stock products": rows(data, "lowStock").length, "Near-expiry batches": rows(data, "nearExpiry").length, "Expired batches": rows(data, "expiredBatches").length }, sections: [{ title: "Current and low stock", columns: cols(["name", "Product"], ["sku", "SKU"], ["category", "Category"], ["currentBaseQty", "Current"], ["availableBaseQty", "Available"], ["reorderLevelBaseQty", "Reorder level"], ["isLowStock", "Low stock"]), rows: mapped(rows(data, "current"), primitive) }, { title: "Batch and near-expiry stock", columns: cols(["product", "Product"], ["sku", "SKU"], ["batchNumber", "Batch"], ["expiryDate", "Expiry"], ["stockBaseQty", "Stock"], ["baseUnit", "Unit"], ["status", "Status"]), rows: mapped(rows(data, "batches"), primitive) }] };
  if (kind === "WRITE_OFFS") return { summary, sections: [{ title: "Expired and damaged stock", columns: cols(["date", "Date"], ["entryNumber", "Entry"], ["type", "Type"], ["product", "Product"], ["sku", "SKU"], ["batch", "Batch"], ["quantityBase", "Quantity"], ["reason", "Reason"], ["user", "User"]), rows: mapped(rows(data, "rows"), (row) => ({ ...primitive(row), product: cell(record(row.product).name), sku: cell(record(row.product).sku), batch: cell(record(row.batch ?? {}).batchNumber), user: cell(record(row.createdBy).displayName) })) }] };
  if (kind === "CUSTOMER_LEDGER" || kind === "SUPPLIER_LEDGER") return { summary: { "Outstanding parties": rows(data, "parties").filter((row) => Number(row.balance) > 0).length, "Report entries": rows(data, "entries").length }, sections: [{ title: kind === "CUSTOMER_LEDGER" ? "Receivables" : "Payables", columns: cols(["code", "Code"], ["name", "Party"], ["periodDebit", "Period debit"], ["periodCredit", "Period credit"], ["balance", "Balance (PKR)"]), rows: mapped(rows(data, "parties").filter((row) => Number(row.balance) > 0), primitive) }, { title: "Ledger entries", columns: cols(["date", "Date"], ["partyName", "Party"], ["entryType", "Type"], ["notes", "Description"], ["debit", "Debit (PKR)"], ["credit", "Credit (PKR)"]), rows: mapped(rows(data, "entries"), (row) => ({ ...primitive(row), partyName: cell(record(row.party).businessName ?? record(row.party).name) })) }] };
  if (kind === "EXPENSES") return { summary: { "Total expenses (PKR)": cell(root.total), "Entries": rows(data, "rows").length }, sections: [{ title: "Expenses", columns: cols(["date", "Date"], ["voucherNumber", "Voucher"], ["category", "Category"], ["description", "Description"], ["method", "Payment"], ["amount", "Amount (PKR)"], ["user", "User"]), rows: mapped(rows(data, "rows"), (row) => ({ ...primitive(row), user: cell(record(row.createdBy).displayName) })) }, { title: "Expense categories", columns: cols(["category", "Category"], ["amount", "Amount (PKR)"]), rows: mapped(rows(data, "categories"), primitive) }] };
  return { summary: Object.fromEntries(Object.entries(record(root.summary ?? {})).map(([key, value]) => [label(key), cell(value)])), sections: [{ title: "Cashbook", columns: cols(["date", "Date"], ["entryNumber", "Entry"], ["entryType", "Type"], ["reference", "Reference"], ["user", "User"], ["cashIn", "Cash in"], ["cashOut", "Cash out"], ["runningBalance", "Running balance"]), rows: mapped(rows(data, "entries"), (row) => ({ date: new Date(String(row.occurredAt)).toLocaleDateString(), entryNumber: cell(row.entryNumber), entryType: cell(row.entryType), reference: cell(record(row.transactionReference ?? {}).number ?? row.reference), user: cell(record(row.createdBy).displayName), cashIn: row.direction === "IN" ? cell(row.amount) : "", cashOut: row.direction === "OUT" ? cell(row.amount) : "", runningBalance: cell(row.runningBalance) })) }] };
}
function primitive(row: Record<string, unknown>) { return Object.fromEntries(Object.entries(row).filter(([key, value]) => !key.endsWith("Minor") && (value == null || ["string", "number", "boolean"].includes(typeof value))).map(([key, value]) => [key, cell(value)])); }
function label(value: string) { return value.replace(/([a-z])([A-Z])/g, "$1 $2").replaceAll("_", " ").replace(/^./, (first) => first.toUpperCase()); }

export function ReportsPage() {
  const token = useAuthStore((state) => state.token)!; const user = useAuthStore((state) => state.user)!; const [kind, setKind] = useState<Kind>("SALES"); const [from, setFrom] = useState(monthStart); const [to, setTo] = useState(today); const [customerId, setCustomerId] = useState(""); const [supplierId, setSupplierId] = useState(""); const [productId, setProductId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [paymentStatus, setPaymentStatus] = useState(""); const [paymentMethod, setPaymentMethod] = useState(""); const [nearExpiryDays, setNearExpiryDays] = useState("30"); const [options, setOptions] = useState<Options>({ customers: [], suppliers: [], products: [], categories: [] }); const [data, setData] = useState<unknown>(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const allowedKinds = kinds.filter((item) => !item.owner || user.role === "OWNER"); const shaped = useMemo(() => data ? shape(kind, data) : { summary: {}, sections: [] }, [kind, data]); const title = allowedKinds.find((item) => item.value === kind)?.label ?? "Report"; const subtitle = kind === "INVENTORY" ? `Near expiry: ${nearExpiryDays} days · Generated ${new Date().toLocaleString()}` : `${from} to ${to} · Generated ${new Date().toLocaleString()}`;
  useEffect(() => { void apiRequest<Options>("/reports/options", {}, token).then(setOptions); }, [token]);
  async function load() { setLoading(true); setMessage(""); try { const query = new URLSearchParams(kind === "INVENTORY" ? { nearExpiryDays, ...(productId ? { productId } : {}), ...(categoryId ? { categoryId } : {}) } : { from, to, ...(customerId && (kind === "SALES" || kind === "CUSTOMER_LEDGER") ? { customerId } : {}), ...(supplierId && (kind === "PURCHASES" || kind === "SUPPLIER_LEDGER") ? { supplierId } : {}), ...(productId && ["SALES", "PURCHASES", "WRITE_OFFS"].includes(kind) ? { productId } : {}), ...(categoryId && ["SALES", "PURCHASES", "WRITE_OFFS"].includes(kind) ? { categoryId } : {}), ...(paymentStatus && ["SALES", "PURCHASES"].includes(kind) ? { paymentStatus } : {}), ...(paymentMethod && ["SALES", "PURCHASES", "EXPENSES", "CASHBOOK"].includes(kind) ? { paymentMethod } : {}) }); setData(await apiRequest(`/reports/${endpoint[kind]}?${query}`, {}, token)); } catch (error) { setData(null); setMessage(error instanceof Error ? error.message : "Report could not be loaded."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [kind]);
  async function action(run: () => Promise<unknown>) { setMessage(""); try { await run(); } catch (error) { setMessage(error instanceof Error ? error.message : "Export failed."); } }
  return <section className="p-8"><div className="mb-6 flex items-start justify-between"><div><p className="mb-1 text-sm font-semibold text-primary">Business intelligence</p><h1 className="m-0 text-3xl font-bold">Essential reports</h1><p className="mt-2 text-sm text-muted-foreground">Operational reports use posted transactions only. Owner reports are protected again at the API.</p></div><div className="flex gap-2"><Button variant="outline" disabled={!shaped.sections.length} onClick={() => exportReportCsv(title, shaped.sections)}><Download className="mr-2" size={17}/>CSV</Button><Button variant="outline" disabled={!shaped.sections.length} onClick={() => void action(() => printReport(title, subtitle, shaped.sections))}><Printer className="mr-2" size={17}/>Print</Button><Button variant="outline" disabled={!shaped.sections.length} onClick={() => void action(() => exportReportPdf(title, subtitle, shaped.sections))}><FileText className="mr-2" size={17}/>PDF</Button></div></div>
    {message && <div className="mb-5 rounded-lg border bg-slate-50 p-3 text-sm">{message}</div>}<Card className="mb-5 p-5"><div className="grid grid-cols-4 gap-3"><label className="text-sm font-medium">Report<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" value={kind} onChange={(event) => { setData(null); setKind(event.target.value as Kind); }}>{allowedKinds.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{kind !== "INVENTORY" && <><label className="text-sm font-medium">From<Input className="mt-1" type="date" value={from} onChange={(event) => setFrom(event.target.value)}/></label><label className="text-sm font-medium">To<Input className="mt-1" type="date" value={to} onChange={(event) => setTo(event.target.value)}/></label></>}{kind === "INVENTORY" && <label className="text-sm font-medium">Near expiry days<Input className="mt-1" type="number" min={1} max={365} value={nearExpiryDays} onChange={(event) => setNearExpiryDays(event.target.value)}/></label>}{["SALES", "CUSTOMER_LEDGER"].includes(kind) && <Select label="Customer" value={customerId} set={setCustomerId} options={options.customers}/>} {["PURCHASES", "SUPPLIER_LEDGER"].includes(kind) && <Select label="Supplier" value={supplierId} set={setSupplierId} options={options.suppliers}/>} {["SALES", "PURCHASES", "INVENTORY", "WRITE_OFFS"].includes(kind) && <><Select label="Category" value={categoryId} set={setCategoryId} options={options.categories}/><Select label="Product" value={productId} set={setProductId} options={options.products.filter((product) => !categoryId || product.categoryId === categoryId)}/></>} {["SALES", "PURCHASES"].includes(kind) && <label className="text-sm font-medium">Settlement<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" value={paymentStatus} onChange={(event) => setPaymentStatus(event.target.value)}><option value="">All</option><option value="PAID">Paid</option><option value="PARTIAL">Partial</option><option value="UNPAID">Credit</option></select></label>} {["SALES", "PURCHASES", "EXPENSES", "CASHBOOK"].includes(kind) && <label className="text-sm font-medium">Payment method<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value)}><option value="">All</option><option value="CASH">Cash</option><option value="BANK_TRANSFER">Bank transfer</option><option value="CARD">Card</option><option value="CHEQUE">Cheque</option><option value="OTHER">Other</option></select></label>}<div className="flex items-end"><Button onClick={() => void load()} disabled={loading}>{loading ? <LoaderCircle className="mr-2 animate-spin" size={17}/> : <RefreshCw className="mr-2" size={17}/>}Run report</Button></div></div></Card>
    {Object.keys(shaped.summary).length > 0 && <div className="mb-5 grid grid-cols-4 gap-3">{Object.entries(shaped.summary).map(([key, value]) => <Card key={key} className="p-4"><p className="m-0 text-xs text-muted-foreground">{key}</p><p className="mb-0 mt-2 text-xl font-bold">{String(value ?? "—")}</p></Card>)}</div>}{loading ? <div className="grid h-52 place-items-center"><LoaderCircle className="animate-spin text-primary"/></div> : shaped.sections.map((section) => <Card key={section.title} className="mb-5 overflow-hidden"><div className="flex items-center gap-2 p-5 pb-2"><BarChart3 size={18}/><h2 className="m-0 text-lg">{section.title}</h2><span className="ml-auto text-xs text-muted-foreground">{section.rows.length} row(s)</span></div><Table><TableHeader><TableRow>{section.columns.map((column) => <TableHead key={column.key}>{column.label}</TableHead>)}</TableRow></TableHeader><TableBody>{section.rows.length ? section.rows.map((row, index) => <TableRow key={index}>{section.columns.map((column) => <TableCell key={column.key}>{String(row[column.key] ?? "—")}</TableCell>)}</TableRow>) : <TableRow><TableCell colSpan={section.columns.length} className="py-8 text-center text-muted-foreground">No data for these filters.</TableCell></TableRow>}</TableBody></Table></Card>)}
  </section>;
}
function Select({ label: title, value, set, options }: { label: string; value: string; set(value: string): void; options: Option[] }) { return <label className="text-sm font-medium">{title}<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" value={value} onChange={(event) => set(event.target.value)}><option value="">All</option>{options.map((option) => <option key={option.id} value={option.id}>{option.businessName ?? option.name}{option.sku ? ` — ${option.sku}` : ""}</option>)}</select></label>; }
