import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRightLeft, LoaderCircle, Plus, Printer, Search, Trash2 } from "lucide-react";
import { useFieldArray, useForm } from "react-hook-form";
import { useState } from "react";
import { createSalesReturnInputSchema, type CreateSalesReturnInput } from "@oil-agency/shared";
import { ApiError, apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { printSalesReturn, type ReturnReceipt } from "@/features/sales-returns/print-service";
import { useAuthStore } from "@/stores/auth-store";

type SearchSale = { id: string; invoiceNumber: string; soldAt: string; total: string; paid: string; customer: { name: string; businessName: string | null } | null; _count: { items: number; returns: number } };
type OriginalSale = { id: string; invoiceNumber: string; soldAt: string; saleType: string; paymentStatus: string; total: string; paid: string; customer: { id: string; name: string; businessName: string | null; code: string } | null; items: Array<{ id: string; productId: string; productName: string; sku: string; baseUnit: string; batchNumber: string | null; batchExpiry: string | null; packingName: string; unitsPerPack: number; soldQuantityBase: number; returnedQuantityBase: number; remainingQuantityBase: number; lineTotal: string }> };
type Replacement = { id: string; name: string; sku: string; baseUnit: string; packUnit: string; unitsPerPack: number; retailPrice: string; wholesalePrice: string; availableBaseQty: number };

const defaults: CreateSalesReturnInput = { saleId: "", reason: "", refundMethod: "CASH", items: [], replacementItems: [] };
export function SalesReturnPage() {
  const token = useAuthStore((state) => state.token)!; const [invoice, setInvoice] = useState(""); const [results, setResults] = useState<SearchSale[]>([]); const [sale, setSale] = useState<OriginalSale | null>(null); const [replacements, setReplacements] = useState<Replacement[]>([]); const [message, setMessage] = useState(""); const [receipt, setReceipt] = useState<ReturnReceipt | null>(null); const [searching, setSearching] = useState(false);
  const form = useForm<CreateSalesReturnInput>({ resolver: zodResolver(createSalesReturnInputSchema), defaultValues: defaults }); const returns = useFieldArray({ control: form.control, name: "items" }); const replacementRows = useFieldArray({ control: form.control, name: "replacementItems" });
  async function search() { if (!invoice.trim()) return; setSearching(true); setMessage(""); try { const result = await apiRequest<{ sales: SearchSale[] }>(`/sales-returns/search?invoice=${encodeURIComponent(invoice.trim())}`, {}, token); setResults(result.sales); if (!result.sales.length) setMessage("No posted invoice matched that number."); } catch (error) { setMessage(error instanceof Error ? error.message : "Invoice search failed."); } finally { setSearching(false); } }
  async function selectSale(id: string) { setMessage(""); try { const [original, options] = await Promise.all([apiRequest<{ sale: OriginalSale }>(`/sales-returns/sales/${id}`, {}, token), apiRequest<{ products: Replacement[] }>("/sales-returns/replacement-options", {}, token)]); setSale(original.sale); setReplacements(options.products); setReceipt(null); form.reset({ ...defaults, saleId: id, refundMethod: original.sale.customer ? "CUSTOMER_LEDGER" : "CASH" }); if (!original.sale.items.length) setMessage("Every item on this invoice has already been returned."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load the invoice."); } }
  function addReturn(item: OriginalSale["items"][number]) { if (form.getValues("items").some((row) => row.saleItemId === item.id)) return; returns.append({ saleItemId: item.id, quantityBase: item.remainingQuantityBase, condition: "RESALABLE" }); }
  async function submit(input: CreateSalesReturnInput) { setMessage(""); try { const result = await apiRequest<{ salesReturn: ReturnReceipt }>("/sales-returns", { method: "POST", body: JSON.stringify(input) }, token); setReceipt(result.salesReturn); setMessage(`Return ${result.salesReturn.returnNumber} posted successfully.`); await selectSale(input.saleId); setReceipt(result.salesReturn); } catch (error) { setMessage(error instanceof ApiError ? error.message : "The return could not be posted."); } }
  const selectedReplacement = form.watch("replacementItems");
  return <section className="p-8"><div className="mb-6"><p className="mb-1 text-sm font-semibold text-primary">Sales</p><h1 className="m-0 text-3xl font-bold">Sales return</h1><p className="mt-2 text-sm text-muted-foreground">Find the original invoice, choose returned goods and post the stock and financial adjustment together.</p></div>
    {message && <div className="mb-5 rounded-lg border bg-slate-50 p-3 text-sm">{message}</div>}
    <Card className="mb-5 p-5"><label className="text-sm font-medium">Original invoice number</label><div className="mt-2 flex max-w-2xl gap-2"><Input value={invoice} onChange={(event) => setInvoice(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void search(); }} placeholder="e.g. SAL-..." autoFocus/><Button type="button" onClick={() => void search()} disabled={searching}>{searching ? <LoaderCircle className="animate-spin" size={18}/> : <Search size={18}/>}<span className="ml-2">Search</span></Button></div>{results.length > 0 && <Table><TableHeader><TableRow><TableHead>Invoice</TableHead><TableHead>Date</TableHead><TableHead>Customer</TableHead><TableHead>Total / paid</TableHead><TableHead>Previous returns</TableHead><TableHead/></TableRow></TableHeader><TableBody>{results.map((row) => <TableRow key={row.id}><TableCell className="font-semibold">{row.invoiceNumber}</TableCell><TableCell>{new Date(row.soldAt).toLocaleDateString()}</TableCell><TableCell>{row.customer?.businessName ?? row.customer?.name ?? "Walk-in"}</TableCell><TableCell>PKR {row.total} / {row.paid}</TableCell><TableCell>{row._count.returns}</TableCell><TableCell><Button size="sm" variant="outline" onClick={() => void selectSale(row.id)}>Select</Button></TableCell></TableRow>)}</TableBody></Table>}</Card>
    {sale && <form onSubmit={form.handleSubmit(submit)}><div className="mb-5 grid grid-cols-[1fr_340px] gap-5"><Card className="p-5"><div className="mb-3 flex items-center justify-between"><h2 className="m-0 text-lg">Invoice {sale.invoiceNumber}</h2><span className="text-sm text-muted-foreground">{sale.customer?.businessName ?? sale.customer?.name ?? "Walk-in customer"}</span></div><Table><TableHeader><TableRow><TableHead>Product / batch</TableHead><TableHead>Sold</TableHead><TableHead>Returned</TableHead><TableHead>Remaining</TableHead><TableHead/></TableRow></TableHeader><TableBody>{sale.items.map((item) => <TableRow key={item.id}><TableCell><strong>{item.productName}</strong><span className="block text-xs text-muted-foreground">{item.sku} · {item.batchNumber ?? "No batch"}</span></TableCell><TableCell>{item.soldQuantityBase} {item.baseUnit}</TableCell><TableCell>{item.returnedQuantityBase}</TableCell><TableCell>{item.remainingQuantityBase}</TableCell><TableCell><Button type="button" size="sm" variant="outline" onClick={() => addReturn(item)} disabled={form.getValues("items").some((row) => row.saleItemId === item.id)}><Plus size={16}/></Button></TableCell></TableRow>)}</TableBody></Table></Card><Card className="p-5"><h2 className="mt-0 text-lg">Adjustment</h2><label className="text-sm font-medium">Refund method<select className="mt-1 h-10 w-full rounded-lg border bg-white px-3" {...form.register("refundMethod")}><option value="CASH">Cash refund</option>{sale.customer && <option value="CUSTOMER_LEDGER">Customer khata</option>}</select></label><label className="mt-4 block text-sm font-medium">Return reason<Textarea className="mt-1" rows={5} {...form.register("reason")} placeholder="Why are the goods being returned?"/></label>{form.formState.errors.reason && <p className="text-xs text-red-600">{form.formState.errors.reason.message}</p>}<p className="mt-4 text-xs text-muted-foreground">Cash refunds are limited to money received on the original invoice. Khata refunds reduce the customer outstanding balance.</p></Card></div>
      <Card className="mb-5 p-5"><h2 className="mt-0 text-lg">Returned goods</h2>{returns.fields.length === 0 ? <p className="text-sm text-muted-foreground">Select at least one original sale item above.</p> : <Table><TableHeader><TableRow><TableHead>Product</TableHead><TableHead>Maximum</TableHead><TableHead>Return quantity</TableHead><TableHead>Condition</TableHead><TableHead/></TableRow></TableHeader><TableBody>{returns.fields.map((field, index) => { const item = sale.items.find((row) => row.id === field.saleItemId)!; return <TableRow key={field.id}><TableCell><strong>{item.productName}</strong><span className="block text-xs text-muted-foreground">{item.batchNumber ?? "No batch"}</span></TableCell><TableCell>{item.remainingQuantityBase} {item.baseUnit}</TableCell><TableCell><Input className="w-32" type="number" min={1} max={item.remainingQuantityBase} {...form.register(`items.${index}.quantityBase`, { valueAsNumber: true })}/></TableCell><TableCell><select className="h-10 rounded-lg border bg-white px-3" {...form.register(`items.${index}.condition`)}><option value="RESALABLE">Resalable</option><option value="DAMAGED">Damaged</option><option value="EXPIRED">Expired</option><option value="OPENED">Opened</option></select></TableCell><TableCell><Button type="button" variant="ghost" onClick={() => returns.remove(index)}><Trash2 size={17}/></Button></TableCell></TableRow>; })}</TableBody></Table>}</Card>
      <Card className="mb-5 p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="m-0 text-lg">Replacement goods</h2><p className="mt-1 text-sm text-muted-foreground">Optional. Replacement value cannot exceed the returned value.</p></div><select className="h-10 max-w-sm rounded-lg border bg-white px-3" defaultValue="" onChange={(event) => { const product = replacements.find((row) => row.id === event.target.value); if (product && !selectedReplacement.some((row) => row.productId === product.id)) replacementRows.append({ productId: product.id, unit: "BASE", quantity: 1 }); event.target.value = ""; }}><option value="">Add replacement product…</option>{replacements.map((product) => <option key={product.id} value={product.id}>{product.name} ({product.availableBaseQty} available)</option>)}</select></div>{replacementRows.fields.length > 0 && <Table><TableHeader><TableRow><TableHead>Product</TableHead><TableHead>Unit</TableHead><TableHead>Quantity</TableHead><TableHead>Price</TableHead><TableHead/></TableRow></TableHeader><TableBody>{replacementRows.fields.map((field, index) => { const product = replacements.find((row) => row.id === field.productId)!; return <TableRow key={field.id}><TableCell><strong>{product.name}</strong><span className="block text-xs text-muted-foreground">{product.sku} · {product.availableBaseQty} {product.baseUnit} available</span></TableCell><TableCell><select className="h-10 rounded-lg border bg-white px-3" {...form.register(`replacementItems.${index}.unit`)}><option value="BASE">{product.baseUnit}</option><option value="PACK">{product.packUnit} ({product.unitsPerPack})</option></select></TableCell><TableCell><Input className="w-28" type="number" min={1} {...form.register(`replacementItems.${index}.quantity`, { valueAsNumber: true })}/></TableCell><TableCell>PKR {sale.saleType === "WHOLESALE" ? product.wholesalePrice : product.retailPrice} / {product.baseUnit}</TableCell><TableCell><Button type="button" variant="ghost" onClick={() => replacementRows.remove(index)}><Trash2 size={17}/></Button></TableCell></TableRow>; })}</TableBody></Table>}</Card>
      <div className="flex justify-end"><Button size="lg" disabled={form.formState.isSubmitting || !returns.fields.length}>{form.formState.isSubmitting ? <LoaderCircle className="mr-2 animate-spin" size={18}/> : <ArrowRightLeft className="mr-2" size={18}/>}Post sales return</Button></div></form>}
    {receipt && <Card className="mt-6 border-primary/30 p-6"><div className="flex items-start justify-between"><div><p className="mb-1 text-sm text-primary">Posted successfully</p><h2 className="m-0">Return receipt {receipt.returnNumber}</h2><p className="mt-2 text-sm text-muted-foreground">Refund/adjustment: PKR {receipt.refund} · {receipt.refundMethod.replace("_", " ")}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void printSalesReturn(receipt, "THERMAL")}><Printer className="mr-2" size={17}/>Thermal</Button><Button variant="outline" onClick={() => void printSalesReturn(receipt, "PDF")}>Save PDF</Button></div></div></Card>}
  </section>;
}
