import { Prisma, type PrismaClient } from "@prisma/client";
import type { PurchaseReturnInput } from "@oil-agency/shared";
import { HttpError } from "../../lib/http-error.js";
import { applyStockMovement } from "../inventory/stock-engine.js";
import { AccountingPostingService } from "../accounting/posting.service.js";
import { minorToMoney } from "../products/product.service.js";

const ref = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
const atNoon = (value: string) => new Date(`${value}T12:00:00.000Z`);
const include = { purchase: { select: { invoiceNumber: true, supplierInvoice: true, purchasedAt: true } }, supplier: { select: { id: true, code: true, name: true } }, createdBy: { select: { displayName: true } }, items: { include: { product: { select: { name: true, sku: true } }, batch: { select: { batchNumber: true } }, purchaseItem: { select: { packingName: true, unitsPerPack: true } } } } } satisfies Prisma.PurchaseReturnInclude;

export class PurchaseReturnService {
  constructor(private readonly db: PrismaClient) {}
  async original(id: string) {
    const purchase = await this.db.purchase.findFirst({ where: { id, status: "POSTED" }, include: { supplier: true, items: { include: { product: { include: { baseUnit: true } }, batch: true, returnItems: { where: { purchaseReturn: { status: "POSTED" } }, select: { quantityBase: true } } } } } });
    if (!purchase) throw new HttpError(404, "PURCHASE_NOT_FOUND", "Posted purchase was not found.");
    return { ...purchase, total: minorToMoney(purchase.totalMinor), items: purchase.items.map((item) => { const returned = item.returnItems.reduce((sum, row) => sum + row.quantityBase, 0); return { id: item.id, productId: item.productId, productName: item.product.name, sku: item.product.sku, batchNumber: item.batch?.batchNumber ?? null, quantityBase: item.quantityBase, returnedQuantityBase: returned, remainingQuantityBase: item.quantityBase - returned, unitCost: minorToMoney(item.unitCostMinor), baseUnit: item.product.baseUnit.symbol }; }).filter((item) => item.remainingQuantityBase > 0) };
  }
  async list() { return this.db.purchaseReturn.findMany({ include, orderBy: { returnedAt: "desc" }, take: 200 }); }
  async get(id: string) { const row = await this.db.purchaseReturn.findUnique({ where: { id }, include }); if (!row) throw new HttpError(404, "PURCHASE_RETURN_NOT_FOUND", "Purchase return was not found."); return dto(row); }
  async create(input: PurchaseReturnInput, userId: string) {
    return this.db.$transaction(async (tx) => {
      const purchase = await tx.purchase.findFirst({ where: { id: input.purchaseId, status: "POSTED" }, include: { items: { include: { product: true, returnItems: { where: { purchaseReturn: { status: "POSTED" } }, select: { quantityBase: true } } } } } });
      if (!purchase) throw new HttpError(404, "PURCHASE_NOT_FOUND", "Posted purchase was not found.");
      const byId = new Map(purchase.items.map((item) => [item.id, item])), seen = new Set<string>();
      let subtotalMinor = 0;
      const prepared = input.items.map((row) => { if (seen.has(row.purchaseItemId)) throw new HttpError(400, "DUPLICATE_RETURN_LINE", "Combine duplicate return lines."); seen.add(row.purchaseItemId); const item = byId.get(row.purchaseItemId); if (!item) throw new HttpError(400, "INVALID_PURCHASE_ITEM", "A selected item is not on the original purchase."); const returned = item.returnItems.reduce((sum, value) => sum + value.quantityBase, 0); if (row.quantityBase > item.quantityBase - returned) throw new HttpError(409, "RETURN_QUANTITY_EXCEEDED", `Only ${Math.max(0, item.quantityBase - returned)} unit(s) remain returnable for ${item.product.name}.`); const unitCostMinor = item.product.averageCostMinor || item.unitCostMinor; const lineTotalMinor = unitCostMinor * row.quantityBase; subtotalMinor += lineTotalMinor; return { row, item, unitCostMinor, lineTotalMinor }; });
      const returnedAt = atNoon(input.returnedOn), taxMinor = purchase.subtotalMinor > 0 ? Math.round(purchase.taxMinor * subtotalMinor / purchase.subtotalMinor) : 0, totalMinor = subtotalMinor + taxMinor;
      if (input.method === "CASH") await AccountingPostingService.assertCashDayOpen(tx, returnedAt);
      const purchaseReturn = await tx.purchaseReturn.create({ data: { returnNumber: ref("PRT"), purchaseId: purchase.id, supplierId: purchase.supplierId, method: input.method, subtotalMinor, taxMinor, totalMinor, reason: input.reason, returnedAt, createdById: userId } });
      for (const row of prepared) { const item = await tx.purchaseReturnItem.create({ data: { purchaseReturnId: purchaseReturn.id, purchaseItemId: row.item.id, productId: row.item.productId, batchId: row.item.batchId, quantityBase: row.row.quantityBase, unitCostMinor: row.unitCostMinor, lineTotalMinor: row.lineTotalMinor } }); await applyStockMovement(tx, { productId: row.item.productId, batchId: row.item.batchId, movementType: "PURCHASE_RETURN", quantityBase: -row.row.quantityBase, unitCostMinor: row.unitCostMinor, sourceType: "PURCHASE_RETURN", sourceId: purchaseReturn.id, sourceLineId: item.id, notes: input.reason, createdById: userId }); }
      await tx.supplierLedger.create({ data: { supplierId: purchase.supplierId, entryType: "PURCHASE_RETURN", debitMinor: totalMinor, creditMinor: 0, sourceType: "PURCHASE_RETURN", sourceId: purchaseReturn.id, purchaseId: purchase.id, notes: `Purchase return ${purchaseReturn.returnNumber}`, occurredAt: returnedAt, createdById: userId } });
      await AccountingPostingService.post(tx, { sourceType: "PURCHASE_RETURN", sourceId: purchaseReturn.id, transactionDate: returnedAt, description: `Purchase return ${purchaseReturn.returnNumber}`, createdById: userId, lines: [{ systemCode: "AP", debitMinor: totalMinor, supplierId: purchase.supplierId }, { systemCode: "INVENTORY", creditMinor: subtotalMinor }, ...(taxMinor ? [{ systemCode: "INPUT_TAX" as const, creditMinor: taxMinor }] : [])] });
      if (input.method === "CASH") { const payment = await tx.payment.create({ data: { receiptNumber: ref("PRR"), direction: "IN", partyType: "SUPPLIER", supplierId: purchase.supplierId, purchaseId: purchase.id, method: "CASH", amountMinor: totalMinor, notes: `Refund for ${purchaseReturn.returnNumber}`, paidAt: returnedAt, createdById: userId } }); await tx.supplierLedger.create({ data: { supplierId: purchase.supplierId, entryType: "PAYMENT", debitMinor: 0, creditMinor: totalMinor, sourceType: "PAYMENT", sourceId: payment.id, purchaseId: purchase.id, paymentId: payment.id, notes: `Cash refund ${payment.receiptNumber}`, occurredAt: returnedAt, createdById: userId } }); await tx.cashbookEntry.create({ data: { entryNumber: ref("CASH"), direction: "IN", entryType: "PURCHASE_RETURN_REFUND", amountMinor: totalMinor, paymentId: payment.id, sourceType: "PAYMENT", sourceId: payment.id, reference: payment.receiptNumber, notes: `Supplier refund ${purchaseReturn.returnNumber}`, occurredAt: returnedAt, createdById: userId } }); await AccountingPostingService.post(tx, { sourceType: "PAYMENT", sourceId: payment.id, transactionDate: returnedAt, description: `Supplier refund ${payment.receiptNumber}`, createdById: userId, lines: [{ systemCode: "CASH", debitMinor: totalMinor }, { systemCode: "AP", creditMinor: totalMinor, supplierId: purchase.supplierId }] }); }
      await tx.auditLog.create({ data: { userId, action: "POST", entityType: "PurchaseReturn", entityId: purchaseReturn.id, afterJson: JSON.stringify({ ...input, totalMinor }) } });
      return dto(await tx.purchaseReturn.findUniqueOrThrow({ where: { id: purchaseReturn.id }, include }));
    });
  }
  async reverse(id: string, reason: string, userId: string) {
    return this.db.$transaction(async (tx) => {
      const value = await tx.purchaseReturn.findUnique({ where: { id }, include: { items: true } }); if (!value) throw new HttpError(404, "PURCHASE_RETURN_NOT_FOUND", "Purchase return was not found."); if (value.status !== "POSTED") throw new HttpError(409, "RETURN_ALREADY_REVERSED", "Purchase return is not posted.");
      const reversedAt = new Date(), payment = value.method === "CASH" ? await tx.payment.findFirst({ where: { notes: { contains: value.returnNumber }, status: "POSTED" }, include: { cashbookEntries: true } }) : null; if (payment) await AccountingPostingService.assertCashDayOpen(tx, reversedAt);
      for (const item of value.items) await applyStockMovement(tx, { productId: item.productId, batchId: item.batchId, movementType: "ADJUSTMENT_IN", quantityBase: item.quantityBase, unitCostMinor: item.unitCostMinor, sourceType: "PURCHASE_RETURN", sourceId: `${value.id}:REVERSAL`, sourceLineId: item.id, notes: reason, createdById: userId });
      const ledgers = await tx.supplierLedger.findMany({ where: { OR: [{ sourceType: "PURCHASE_RETURN", sourceId: value.id }, ...(payment ? [{ sourceType: "PAYMENT" as const, sourceId: payment.id }] : [])] }, include: { reversalEntry: true } }); for (const entry of ledgers) if (!entry.reversalEntry) await tx.supplierLedger.create({ data: { supplierId: entry.supplierId, entryType: "REVERSAL", debitMinor: entry.creditMinor, creditMinor: entry.debitMinor, sourceType: "SUPPLIER_LEDGER_REVERSAL", sourceId: entry.id, reversalOfEntryId: entry.id, notes: reason, occurredAt: reversedAt, createdById: userId } });
      if (payment) { await tx.payment.update({ where: { id: payment.id }, data: { status: "VOIDED" } }); for (const cash of payment.cashbookEntries) await tx.cashbookEntry.create({ data: { entryNumber: ref("CASH"), direction: cash.direction === "IN" ? "OUT" : "IN", entryType: "ADJUSTMENT", amountMinor: cash.amountMinor, sourceType: "CASHBOOK", sourceId: cash.id, reversalOfId: cash.id, notes: reason, occurredAt: reversedAt, createdById: userId } }); const paymentJournal = await tx.journalEntry.findUnique({ where: { sourceType_sourceId_postingKey: { sourceType: "PAYMENT", sourceId: payment.id, postingKey: "PRIMARY" } } }); if (paymentJournal) await AccountingPostingService.reverse(tx, paymentJournal.id, reason, userId, reversedAt); }
      const journal = await tx.journalEntry.findUnique({ where: { sourceType_sourceId_postingKey: { sourceType: "PURCHASE_RETURN", sourceId: value.id, postingKey: "PRIMARY" } } }); if (journal) await AccountingPostingService.reverse(tx, journal.id, reason, userId, reversedAt); await tx.purchaseReturn.update({ where: { id }, data: { status: "VOIDED" } }); await tx.auditLog.create({ data: { userId, action: "REVERSE", entityType: "PurchaseReturn", entityId: id, beforeJson: JSON.stringify({ status: "POSTED" }), afterJson: JSON.stringify({ status: "VOIDED", reason }) } }); return { id, status: "VOIDED" as const };
    });
  }
}
type ReturnRecord = Prisma.PurchaseReturnGetPayload<{ include: typeof include }>;
function dto(row: ReturnRecord) { return { ...row, subtotal: minorToMoney(row.subtotalMinor), tax: minorToMoney(row.taxMinor), total: minorToMoney(row.totalMinor), items: row.items.map((item) => ({ ...item, unitCost: minorToMoney(item.unitCostMinor), lineTotal: minorToMoney(item.lineTotalMinor) })) }; }
