import type { AppDbClient, TransactionClient, PaymentMethod, SourceType, StockMovementType, BackupKind, JobType, JobStatus, CashDirection, CashbookEntryType, ReturnCondition } from "../../lib/db.js";
import { businessSettingSchema, DEFAULT_BUSINESS_SETTING, type CustomerPaymentInput } from "@oil-agency/shared";
import { HttpError } from "../../lib/http-error.js";
import { moneyToMinor, minorToMoney } from "../products/product.service.js";
import { AccountingPostingService } from "../accounting/posting.service.js";
const ref = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
const atNoon = (value: string) => new Date(`${value}T12:00:00.000Z`);
function business(valueJson?: string) { try { return businessSettingSchema.catch(DEFAULT_BUSINESS_SETTING).parse(valueJson ? JSON.parse(valueJson) : undefined); } catch { return DEFAULT_BUSINESS_SETTING; } }
export class CustomerPaymentService { constructor(private readonly db: AppDbClient) {} async receive(customerId: string, input: CustomerPaymentInput, userId: string) { const amountMinor = moneyToMinor(input.amount); if (amountMinor <= 0) throw new HttpError(400, "INVALID_PAYMENT", "Payment must be greater than zero."); return this.db.$transaction(async (tx) => { const customer = await tx.customer.findFirst({ where: { id: customerId, isActive: true, deletedAt: null } }); if (!customer) throw new HttpError(404, "CUSTOMER_NOT_FOUND", "Active customer was not found."); const paidAt = atNoon(input.paidAt); if (input.method === "CASH") await AccountingPostingService.assertCashDayOpen(tx, paidAt); const payment = await tx.payment.create({ data: { receiptNumber: ref("CR"), direction: "IN", partyType: "CUSTOMER", customerId, method: input.method as PaymentMethod, amountMinor, reference: input.reference ?? null, notes: input.notes ?? null, paidAt, createdById: userId } }); const ledger = await tx.customerLedger.create({ data: { customerId, entryType: "PAYMENT", debitMinor: 0, creditMinor: amountMinor, sourceType: "PAYMENT", sourceId: payment.id, paymentId: payment.id, notes: input.notes ?? `Payment ${payment.receiptNumber}`, occurredAt: paidAt, createdById: userId } }); if (input.method === "CASH") await tx.cashbookEntry.create({ data: { entryNumber: ref("CASH"), direction: "IN", entryType: "CUSTOMER_RECOVERY", amountMinor, paymentId: payment.id, sourceType: "PAYMENT", sourceId: payment.id, reference: payment.receiptNumber, notes: `Customer receipt ${payment.receiptNumber}`, occurredAt: paidAt, createdById: userId } }); const tenderAccountId = await AccountingPostingService.tenderAccountId(tx, input.method as PaymentMethod, payment.bankAccountId); await AccountingPostingService.post(tx, { sourceType: "PAYMENT", sourceId: payment.id, transactionDate: paidAt, description: `Customer receipt ${payment.receiptNumber}`, createdById: userId, lines: [{ accountId: tenderAccountId, debitMinor: amountMinor, customerId }, { systemCode: "AR", creditMinor: amountMinor, customerId }] }); await tx.auditLog.create({ data: { userId, action: "POST", entityType: "CustomerPayment", entityId: payment.id, afterJson: JSON.stringify({ customerId, amountMinor, ledgerEntryId: ledger.id }) } }); const setting = await tx.setting.findUnique({ where: { key: "business" }, select: { valueJson: true } }); return { ...payment, amount: minorToMoney(payment.amountMinor), customer: { id: customer.id, name: customer.name, businessName: customer.businessName }, business: business(setting?.valueJson) }; }); } }
