import { Prisma, type Customer, type PrismaClient } from "@prisma/client";
import type { CreateCustomerInput, CustomerListQuery, UpdateCustomerInput } from "@oil-agency/shared";
import { HttpError } from "../../lib/http-error.js";
import { moneyToMinor, minorToMoney } from "../products/product.service.js";
import { aging, ledgerBalanceMinor } from "./customer-ledger.service.js";
import { AccountingPostingService } from "../accounting/posting.service.js";

const code = () => `CUS-${Date.now()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`;
export function signedMoneyToMinor(value: string) { return value.startsWith("-") ? -moneyToMinor(value.slice(1)) : moneyToMinor(value); }
export class CustomerService {
  constructor(private readonly db: PrismaClient) {}
  async list(query: CustomerListQuery) { const where: Prisma.CustomerWhereInput = { deletedAt: null, ...(query.active === "ACTIVE" ? { isActive: true } : query.active === "INACTIVE" ? { isActive: false } : {}), ...(query.customerType ? { customerType: query.customerType } : {}), ...(query.search ? { OR: [{ name: { contains: query.search } }, { businessName: { contains: query.search } }, { phone: { contains: query.search } }, { whatsapp: { contains: query.search } }, { code: { contains: query.search } }, { taxIdentifier: { contains: query.search } }] } : {}) }; const [customers, total] = await this.db.$transaction([this.db.customer.findMany({ where, orderBy: { name: "asc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), this.db.customer.count({ where })]); const entries = await this.db.customerLedger.findMany({ where: { customerId: { in: customers.map((customer) => customer.id) } }, select: { customerId: true, debitMinor: true, creditMinor: true, dueDate: true, occurredAt: true } }); return { customers: customers.map((customer) => { const own = entries.filter((entry) => entry.customerId === customer.id); const balanceMinor = ledgerBalanceMinor(own); const age = aging(own); return this.dto(customer, balanceMinor, age.overdueMinor); }), pagination: { page: query.page, pageSize: query.pageSize, total, pages: Math.max(1, Math.ceil(total / query.pageSize)) } }; }
  async get(id: string) { const customer = await this.db.customer.findFirst({ where: { id, deletedAt: null } }); if (!customer) throw new HttpError(404, "CUSTOMER_NOT_FOUND", "Customer was not found."); const entries = await this.db.customerLedger.findMany({ where: { customerId: id }, select: { debitMinor: true, creditMinor: true, dueDate: true, occurredAt: true } }); const age = aging(entries); return this.dto(customer, ledgerBalanceMinor(entries), age.overdueMinor); }
  async create(input: CreateCustomerInput, userId: string) { const openingBalanceMinor = signedMoneyToMinor(input.openingBalance); try { return await this.db.$transaction(async (tx) => { const customer = await tx.customer.create({ data: { code: code(), name: input.name, businessName: input.businessName || null, phone: input.phone || null, whatsapp: input.whatsapp || null, address: input.address || null, taxIdentifier: input.taxIdentifier || null, customerType: input.customerType, openingBalanceMinor, paymentTermsDays: input.paymentTermsDays, isActive: input.isActive } }); if (openingBalanceMinor !== 0) { await tx.customerLedger.create({ data: { customerId: customer.id, entryType: "OPENING_BALANCE", debitMinor: Math.max(0, openingBalanceMinor), creditMinor: Math.max(0, -openingBalanceMinor), sourceType: "CUSTOMER", sourceId: customer.id, notes: "Opening balance", createdById: userId } }); await AccountingPostingService.post(tx, { sourceType: "CUSTOMER", sourceId: customer.id, transactionDate: new Date(), description: `Opening balance - ${customer.name}`, createdById: userId, lines: openingBalanceMinor > 0 ? [{ systemCode: "AR", debitMinor: openingBalanceMinor, customerId: customer.id }, { systemCode: "OPENING_EQUITY", creditMinor: openingBalanceMinor }] : [{ systemCode: "OPENING_EQUITY", debitMinor: -openingBalanceMinor }, { systemCode: "AR", creditMinor: -openingBalanceMinor, customerId: customer.id }] }); } await tx.auditLog.create({ data: { userId, action: "CREATE", entityType: "Customer", entityId: customer.id, afterJson: JSON.stringify(input) } }); return this.dto(customer, openingBalanceMinor, 0); }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new HttpError(409, "DUPLICATE_CUSTOMER", "Customer code already exists. Try again."); throw error; } }
  async update(id: string, input: UpdateCustomerInput, userId: string) { const before = await this.db.customer.findFirst({ where: { id, deletedAt: null } }); if (!before) throw new HttpError(404, "CUSTOMER_NOT_FOUND", "Customer was not found."); const customer = await this.db.$transaction(async (tx) => { const updated = await tx.customer.update({ where: { id }, data: { name: input.name, businessName: input.businessName || null, phone: input.phone || null, whatsapp: input.whatsapp || null, address: input.address || null, taxIdentifier: input.taxIdentifier || null, customerType: input.customerType, paymentTermsDays: input.paymentTermsDays, isActive: input.isActive } }); await tx.auditLog.create({ data: { userId, action: "UPDATE", entityType: "Customer", entityId: id, beforeJson: JSON.stringify(before), afterJson: JSON.stringify(input) } }); return updated; }); const entries = await this.db.customerLedger.findMany({ where: { customerId: id }, select: { debitMinor: true, creditMinor: true, dueDate: true, occurredAt: true } }); return this.dto(customer, ledgerBalanceMinor(entries), aging(entries).overdueMinor); }
  async remove(id: string, userId: string) { const customer = await this.db.customer.findFirst({ where: { id, deletedAt: null } }); if (!customer) throw new HttpError(404, "CUSTOMER_NOT_FOUND", "Customer was not found."); const entries = await this.db.customerLedger.findMany({ where: { customerId: id }, select: { debitMinor: true, creditMinor: true } }); if (ledgerBalanceMinor(entries) !== 0) throw new HttpError(409, "CUSTOMER_HAS_BALANCE", "A customer with a non-zero khata balance cannot be deleted."); await this.db.$transaction([this.db.customer.update({ where: { id }, data: { isActive: false, deletedAt: new Date() } }), this.db.auditLog.create({ data: { userId, action: "SOFT_DELETE", entityType: "Customer", entityId: id, beforeJson: JSON.stringify(customer) } })]); }
  async recovery() { const customers = await this.db.customer.findMany({ where: { isActive: true, deletedAt: null }, orderBy: { name: "asc" } }); const entries = await this.db.customerLedger.findMany({ where: { customerId: { in: customers.map((customer) => customer.id) } }, select: { customerId: true, debitMinor: true, creditMinor: true, dueDate: true, occurredAt: true } }); return customers.map((customer) => { const own = entries.filter((entry) => entry.customerId === customer.id), age = aging(own); return { id: customer.id, code: customer.code, name: customer.name, businessName: customer.businessName, phone: customer.phone, whatsapp: customer.whatsapp, balance: minorToMoney(ledgerBalanceMinor(own)), overdue: minorToMoney(age.overdueMinor), earliestDueDate: age.earliestDueDate?.toISOString() ?? null }; }).filter((customer) => Number(customer.overdue) > 0).sort((a, b) => Number(b.overdue) - Number(a.overdue)); }
  private dto(customer: Customer, balanceMinor: number, overdueMinor: number) { const { creditLimitMinor: _creditLimitMinor, openingBalanceMinor, ...details } = customer; return { ...details, openingBalance: minorToMoney(openingBalanceMinor), balance: minorToMoney(balanceMinor), overdue: minorToMoney(overdueMinor) }; }
}
