import type { CustomerLedger, PrismaClient } from "@prisma/client";
import type { ManualLedgerInput } from "@oil-agency/shared";
import { HttpError } from "../../lib/http-error.js";
import { moneyToMinor, minorToMoney } from "../products/product.service.js";
import { AccountingPostingService } from "../accounting/posting.service.js";

const ref = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
const atNoon = (value: string) => new Date(`${value}T12:00:00.000Z`);
export const ledgerBalanceMinor = (entries: Array<Pick<CustomerLedger, "debitMinor" | "creditMinor">>) => entries.reduce((sum, entry) => sum + entry.debitMinor - entry.creditMinor, 0);
export function aging(entries: Array<Pick<CustomerLedger, "debitMinor" | "creditMinor" | "dueDate" | "occurredAt">>, asOf = new Date()) {
  const debts: Array<{ remaining: number; dueDate: Date | null }> = []; let unappliedCredit = 0;
  for (const entry of [...entries].sort((a, b) => a.occurredAt.valueOf() - b.occurredAt.valueOf())) { let debit = entry.debitMinor; if (debit > 0 && unappliedCredit) { const used = Math.min(debit, unappliedCredit); debit -= used; unappliedCredit -= used; } if (debit) debts.push({ remaining: debit, dueDate: entry.dueDate }); let credit = entry.creditMinor; for (const debt of debts) { if (!credit) break; const used = Math.min(credit, debt.remaining); debt.remaining -= used; credit -= used; } unappliedCredit += credit; }
  const start = new Date(asOf); start.setHours(0, 0, 0, 0); return { overdueMinor: debts.filter((debt) => debt.remaining > 0 && debt.dueDate && debt.dueDate < start).reduce((sum, debt) => sum + debt.remaining, 0), earliestDueDate: debts.filter((debt) => debt.remaining > 0 && debt.dueDate).sort((a, b) => a.dueDate!.valueOf() - b.dueDate!.valueOf())[0]?.dueDate ?? null };
}
export class CustomerLedgerService {
  constructor(private readonly db: PrismaClient) {}
  async statement(customerId: string, from?: string, to?: string) { const customer = await this.db.customer.findFirst({ where: { id: customerId, deletedAt: null } }); if (!customer) throw new HttpError(404, "CUSTOMER_NOT_FOUND", "Customer was not found."); const all = await this.db.customerLedger.findMany({ where: { customerId, ...(to ? { occurredAt: { lte: new Date(`${to}T23:59:59.999Z`) } } : {}) }, include: { sale: { select: { id: true, invoiceNumber: true } }, payment: { select: { receiptNumber: true, method: true } }, createdBy: { select: { displayName: true } }, reversalEntry: { select: { id: true } } }, orderBy: [{ occurredAt: "asc" }, { createdAt: "asc" }] }); const fromDate = from ? atNoon(from) : null; let running = 0; const entries = []; for (const entry of all) { const previousBalanceMinor = running; running += entry.debitMinor - entry.creditMinor; if (!fromDate || entry.occurredAt >= fromDate) entries.push({ ...entry, debit: minorToMoney(entry.debitMinor), credit: minorToMoney(entry.creditMinor), previousBalance: minorToMoney(previousBalanceMinor), currentBalance: minorToMoney(running) }); } const previousBalanceMinor = fromDate ? ledgerBalanceMinor(all.filter((entry) => entry.occurredAt < fromDate)) : 0; const age = aging(all); const { creditLimitMinor: _creditLimitMinor, openingBalanceMinor, ...customerDetails } = customer; return { customer: { ...customerDetails, openingBalance: minorToMoney(openingBalanceMinor) }, entries, previousBalance: minorToMoney(previousBalanceMinor), currentBalance: minorToMoney(running), overdue: minorToMoney(age.overdueMinor), earliestDueDate: age.earliestDueDate?.toISOString() ?? null };
  }
  async replace(customerId: string, entryId: string, input: ManualLedgerInput, userId: string) {
    const amountMinor = moneyToMinor(input.amount);
    if (amountMinor <= 0) throw new HttpError(400, "INVALID_AMOUNT", "Amount must be greater than zero.");
    return this.db.$transaction(async (tx) => {
      const original = await tx.customerLedger.findFirst({ where: { id: entryId, customerId }, include: { reversalEntry: true } });
      if (!original) throw new HttpError(404, "LEDGER_ENTRY_NOT_FOUND", "Khata entry was not found.");
      if (!['MANUAL_DEBIT', 'MANUAL_CREDIT'].includes(original.entryType)) throw new HttpError(409, "MANUAL_ENTRY_REQUIRED", "Only manual khata entries can be edited here.");
      if (original.reversalEntry) throw new HttpError(409, "ENTRY_ALREADY_REVERSED", "This khata entry has already been deleted or replaced.");
      const journal = await tx.journalEntry.findFirst({ where: { sourceId: original.sourceId, sourceType: original.sourceType, postingKey: "PRIMARY" }, include: { lines: true } });
      const changedAt = new Date();
      const reversal = await tx.customerLedger.create({ data: { customerId, entryType: "REVERSAL", debitMinor: original.creditMinor, creditMinor: original.debitMinor, sourceType: "LEDGER_REVERSAL", sourceId: original.id, notes: `Edited: ${input.reason}`, occurredAt: changedAt, reversalOfEntryId: original.id, createdById: userId } });
      if (journal) await AccountingPostingService.reverse(tx, journal.id, `Khata entry edited: ${input.reason}`, userId, changedAt);
      const sourceId = ref("KHATA");
      const occurredAt = atNoon(input.occurredAt);
      const entry = await tx.customerLedger.create({ data: { customerId, entryType: input.direction === "DEBIT" ? "MANUAL_DEBIT" : "MANUAL_CREDIT", debitMinor: input.direction === "DEBIT" ? amountMinor : 0, creditMinor: input.direction === "CREDIT" ? amountMinor : 0, sourceType: "CUSTOMER_ADJUSTMENT", sourceId, notes: input.reason, dueDate: input.dueDate ? atNoon(input.dueDate) : null, occurredAt, createdById: userId } });
      const offsetAccountId = input.offsetAccountId ?? journal?.lines.find((line) => !line.customerId)?.accountId ?? await AccountingPostingService.accountId(tx, "OPENING_EQUITY");
      await AccountingPostingService.post(tx, { sourceType: "CUSTOMER_ADJUSTMENT", sourceId, transactionDate: occurredAt, description: input.reason, createdById: userId, lines: input.direction === "DEBIT" ? [{ systemCode: "AR", debitMinor: amountMinor, customerId }, { accountId: offsetAccountId, creditMinor: amountMinor }] : [{ accountId: offsetAccountId, debitMinor: amountMinor }, { systemCode: "AR", creditMinor: amountMinor, customerId }] });
      await tx.auditLog.create({ data: { userId, action: "UPDATE", entityType: "CustomerLedger", entityId: entry.id, beforeJson: JSON.stringify({ id: original.id, debitMinor: original.debitMinor, creditMinor: original.creditMinor, notes: original.notes, occurredAt: original.occurredAt, dueDate: original.dueDate }), afterJson: JSON.stringify({ id: entry.id, direction: input.direction, amountMinor, reason: input.reason, reversalId: reversal.id }) } });
      return entry;
    });
  }
  async reverse(customerId: string, entryId: string, reason: string, userId: string) { return this.db.$transaction(async (tx) => { const original = await tx.customerLedger.findFirst({ where: { id: entryId, customerId }, include: { reversalEntry: true } }); if (!original) throw new HttpError(404, "LEDGER_ENTRY_NOT_FOUND", "Ledger entry was not found."); if (original.entryType === "REVERSAL" || original.reversalEntry) throw new HttpError(409, "ENTRY_ALREADY_REVERSED", "This entry is already a reversal or has already been reversed."); if (!["MANUAL_DEBIT", "MANUAL_CREDIT", "OPENING_BALANCE"].includes(original.entryType)) throw new HttpError(409, "SOURCE_REVERSAL_REQUIRED", "Reverse this entry from its original sale, payment, or return."); const reversal = await tx.customerLedger.create({ data: { customerId: original.customerId, entryType: "REVERSAL", debitMinor: original.creditMinor, creditMinor: original.debitMinor, sourceType: "LEDGER_REVERSAL", sourceId: original.id, notes: `Reversal: ${reason}`, occurredAt: new Date(), reversalOfEntryId: original.id, createdById: userId } }); const journal = await tx.journalEntry.findFirst({ where: { sourceId: original.sourceId, sourceType: original.sourceType, postingKey: "PRIMARY" } }); if (journal) await AccountingPostingService.reverse(tx, journal.id, reason, userId); await tx.auditLog.create({ data: { userId, action: "REVERSE", entityType: "CustomerLedgerReversal", entityId: reversal.id, beforeJson: JSON.stringify({ originalEntryId: original.id }), afterJson: JSON.stringify({ reason }) } }); return reversal; }); }
}
