import type { PrismaClient } from "@prisma/client";
import { pakistanDay } from "../cashbook/cashbook.service.js";
import { minorToMoney } from "../products/product.service.js";

const pakistanDate = (date = new Date()) => { const parts = Object.fromEntries(new Intl.DateTimeFormat("en", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; };
export function classifyDashboardStock(product: { stockOnHandBaseQty: number; reorderLevelBaseQty: number; batches: Array<{ stockOnHandBaseQty: number; expiryDate: Date | null }> }, today: Date, nearDate: Date) { const expiredBaseQty = product.batches.filter((batch) => batch.expiryDate && batch.expiryDate < today).reduce((sum, batch) => sum + batch.stockOnHandBaseQty, 0); const availableBaseQty = Math.max(0, product.stockOnHandBaseQty - expiredBaseQty); return { availableBaseQty, isLow: availableBaseQty <= product.reorderLevelBaseQty, isNearExpiry: product.batches.some((batch) => batch.stockOnHandBaseQty > 0 && batch.expiryDate && batch.expiryDate >= today && batch.expiryDate <= nearDate), isExpired: expiredBaseQty > 0, expiredBaseQty };
}
export function outstandingBalance(debitMinor: number | null, creditMinor: number | null, payable = false) { const value = payable ? (creditMinor ?? 0) - (debitMinor ?? 0) : (debitMinor ?? 0) - (creditMinor ?? 0); return Math.max(0, value); }

export class DashboardService {
  constructor(private readonly db: PrismaClient) {}
  async get() {
    const date = pakistanDate(); const day = pakistanDay(date); const today = day.start; const nearDate = new Date(today.getTime() + 30 * 86_400_000);
    const [invoiceCount, products, damageAlertCount, damageAlerts, customerBalances, supplierBalances, recentSales, recentPurchases, lastBackup] = await Promise.all([
      this.db.sale.count({ where: { status: "POSTED", soldAt: { gte: day.start, lte: day.end } } }),
      this.db.product.findMany({ where: { deletedAt: null, isActive: true }, select: { id: true, name: true, sku: true, stockOnHandBaseQty: true, reorderLevelBaseQty: true, baseUnit: { select: { symbol: true } }, batches: { where: { stockOnHandBaseQty: { gt: 0 } }, select: { batchNumber: true, stockOnHandBaseQty: true, expiryDate: true } } }, orderBy: { name: "asc" } }),
      this.db.damageEntry.count({ where: { type: "DAMAGED" } }),
      this.db.damageEntry.findMany({ where: { type: "DAMAGED" }, select: { id: true, entryNumber: true, quantityBase: true, reason: true, occurredAt: true, product: { select: { name: true, sku: true, baseUnit: { select: { symbol: true } } } }, batch: { select: { batchNumber: true } } }, orderBy: { occurredAt: "desc" }, take: 5 }),
      this.db.customerLedger.groupBy({ by: ["customerId"], _sum: { debitMinor: true, creditMinor: true } }),
      this.db.supplierLedger.groupBy({ by: ["supplierId"], _sum: { debitMinor: true, creditMinor: true } }),
      this.db.sale.findMany({ where: { status: "POSTED" }, select: { id: true, invoiceNumber: true, soldAt: true, paymentStatus: true, customer: { select: { name: true, businessName: true } }, createdBy: { select: { displayName: true } } }, orderBy: { soldAt: "desc" }, take: 6 }),
      this.db.purchase.findMany({ where: { status: "POSTED" }, select: { id: true, invoiceNumber: true, supplierInvoice: true, purchasedAt: true, paymentStatus: true, supplier: { select: { name: true, businessName: true } }, createdBy: { select: { displayName: true } } }, orderBy: { purchasedAt: "desc" }, take: 6 }),
      this.db.auditLog.findFirst({ where: { action: "BACKUP" }, select: { id: true, createdAt: true, user: { select: { displayName: true } } }, orderBy: { createdAt: "desc" } }),
    ]);
    const stock = products.map((product) => ({ product, state: classifyDashboardStock(product, today, nearDate) }));
    const customerPending = customerBalances.map((row) => ({ id: row.customerId, balanceMinor: outstandingBalance(row._sum.debitMinor, row._sum.creditMinor) })).filter((row) => row.balanceMinor > 0).sort((a, b) => b.balanceMinor - a.balanceMinor); const supplierPending = supplierBalances.map((row) => ({ id: row.supplierId, balanceMinor: outstandingBalance(row._sum.debitMinor, row._sum.creditMinor, true) })).filter((row) => row.balanceMinor > 0).sort((a, b) => b.balanceMinor - a.balanceMinor);
    const [customers, suppliers] = await Promise.all([this.db.customer.findMany({ where: { id: { in: customerPending.slice(0, 6).map((row) => row.id) } }, select: { id: true, code: true, name: true, businessName: true, phone: true } }), this.db.supplier.findMany({ where: { id: { in: supplierPending.slice(0, 6).map((row) => row.id) } }, select: { id: true, code: true, name: true, businessName: true, phone: true } })]); const customerById = new Map(customers.map((row) => [row.id, row])); const supplierById = new Map(suppliers.map((row) => [row.id, row]));
    return { businessDate: date, cards: { todayInvoiceCount: invoiceCount, lowStockProducts: stock.filter((row) => row.state.isLow).length, nearExpiryProducts: stock.filter((row) => row.state.isNearExpiry).length, expiredProducts: stock.filter((row) => row.state.isExpired).length, damagedAlerts: damageAlertCount, pendingCustomerPayments: customerPending.length, pendingSupplierPayments: supplierPending.length }, lowStock: stock.filter((row) => row.state.isLow).slice(0, 6).map(({ product, state }) => ({ id: product.id, name: product.name, sku: product.sku, availableBaseQty: state.availableBaseQty, reorderLevelBaseQty: product.reorderLevelBaseQty, baseUnit: product.baseUnit.symbol })), expiryAlerts: stock.filter((row) => row.state.isNearExpiry || row.state.isExpired).flatMap(({ product }) => product.batches.filter((batch) => batch.expiryDate && batch.stockOnHandBaseQty > 0 && batch.expiryDate <= nearDate).map((batch) => ({ productId: product.id, product: product.name, sku: product.sku, batchNumber: batch.batchNumber, expiryDate: batch.expiryDate!.toISOString(), stockBaseQty: batch.stockOnHandBaseQty, status: batch.expiryDate! < today ? "EXPIRED" : "NEAR_EXPIRY" }))).sort((a, b) => a.expiryDate.localeCompare(b.expiryDate)).slice(0, 6), damageAlerts: damageAlerts.map((row) => ({ ...row, occurredAt: row.occurredAt.toISOString() })), pendingCustomers: customerPending.slice(0, 6).map((row) => ({ ...customerById.get(row.id)!, outstanding: minorToMoney(row.balanceMinor) })), pendingSuppliers: supplierPending.slice(0, 6).map((row) => ({ ...supplierById.get(row.id)!, outstanding: minorToMoney(row.balanceMinor) })), recentSales, recentPurchases, backup: lastBackup ? { status: "COMPLETED", createdAt: lastBackup.createdAt.toISOString(), createdBy: lastBackup.user?.displayName ?? "System" } : { status: "NEVER", createdAt: null, createdBy: null } };
  }
}
