import cors from "cors";
import express from "express";
import helmet from "helmet";
import type { PrismaClient } from "@prisma/client";
import { prisma } from "./lib/prisma.js";
import { errorHandler } from "./middleware/error-handler.js";
import { createAuthRouter } from "./modules/auth/auth.routes.js";
import { createUsersRouter } from "./modules/users/users.routes.js";
import { createApprovalsRouter } from "./modules/approvals/approvals.routes.js";
import { createSettingsRouter } from "./modules/settings/settings.routes.js";
import { createProductRouter } from "./modules/products/product.routes.js";
import { createInventoryRouter } from "./modules/inventory/inventory.routes.js";
import { createPurchaseRouter } from "./modules/purchases/purchase.routes.js";
import { createSaleRouter } from "./modules/sales/sale.routes.js";
import { createCustomerRouter } from "./modules/customers/customer.routes.js";
import { createSupplierRouter } from "./modules/suppliers/supplier.routes.js";
import { createSalesReturnRouter } from "./modules/sales-returns/sales-return.routes.js";
import { createCashbookRouter } from "./modules/cashbook/cashbook.routes.js";
import { createReportRouter } from "./modules/reports/report.routes.js";
import { createDashboardRouter } from "./modules/dashboard/dashboard.routes.js";
import { createExpenseRouter } from "./modules/expenses/expense.routes.js";
import { createAccountingRouter } from "./modules/accounting/accounting.routes.js";
import { createPurchaseReturnRouter } from "./modules/purchase-returns/purchase-return.routes.js";

export function createApp(db: PrismaClient = prisma) {
  const app = express();
  app.disable("x-powered-by");
  app.use(helmet());
  app.use(cors({ origin: [/^http:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/, "null"], methods: ["GET", "POST", "PUT", "PATCH", "DELETE"] }));
  app.use(express.json({ limit: "2mb" }));
  app.get("/api/health", (_req, res) => res.json({ status: "ok" }));
  app.use("/api/auth", createAuthRouter(db));
  app.use("/api/users", createUsersRouter(db));
  app.use("/api/approvals", createApprovalsRouter(db));
  app.use("/api/settings", createSettingsRouter(db));
  app.use("/api/products", createProductRouter(db));
  app.use("/api/inventory", createInventoryRouter(db));
  app.use("/api/purchases", createPurchaseRouter(db));
  app.use("/api/pos", createSaleRouter(db));
  app.use("/api/customers", createCustomerRouter(db));
  app.use("/api/suppliers", createSupplierRouter(db));
  app.use("/api/sales-returns", createSalesReturnRouter(db));
  app.use("/api/cashbook", createCashbookRouter(db));
  app.use("/api/expenses", createExpenseRouter(db));
  app.use("/api/reports", createReportRouter(db));
  app.use("/api/dashboard", createDashboardRouter(db));
  app.use("/api/accounting", createAccountingRouter(db));
  app.use("/api/purchase-returns", createPurchaseReturnRouter(db));
  app.use((_req, res) => res.status(404).json({ error: { code: "NOT_FOUND", message: "Resource was not found." } }));
  app.use(errorHandler);
  return app;
}
