import type { PrismaClient, StockMovementType } from "@prisma/client";
import type { CartonOpenInput, InventoryAdjustmentInput, InventoryWriteOffInput, StockCountInput } from "@oil-agency/shared";
import { HttpError } from "../../lib/http-error.js";
import { applyStockMovement, toBaseQuantity } from "./stock-engine.js";
import { AccountingPostingService } from "../accounting/posting.service.js";

const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
const startOfToday = () => { const date = new Date(); date.setHours(0, 0, 0, 0); return date; };

export class InventoryService {
  constructor(private readonly db: PrismaClient) {}

  async stock(search = "", lowOnly = false, includeInactive = false) {
    const products = await this.db.product.findMany({ where: { deletedAt: null, ...(!includeInactive ? { isActive: true } : {}), ...(search ? { OR: [{ name: { contains: search } }, { sku: { contains: search } }, { barcode: { contains: search } }] } : {}) }, include: { baseUnit: true, packings: { where: { isActive: true }, orderBy: { unitsPerPack: "desc" } }, batches: { orderBy: { expiryDate: "asc" } }, stockMovements: { where: { movementType: { in: ["OPENING_STOCK", "SALES_RETURN", "DAMAGE", "EXPIRY"] } }, select: { movementType: true, quantityBase: true } } }, orderBy: { name: "asc" } });
    const today = startOfToday();
    return products.map((p) => {
      const batches = p.batches.map((b) => { const isExpired = Boolean(b.expiryDate && b.expiryDate < today); return { id: b.id, batchNumber: b.batchNumber, expiryDate: b.expiryDate?.toISOString() ?? null, stockBaseQty: b.stockOnHandBaseQty, availableBaseQty: isExpired ? 0 : b.stockOnHandBaseQty, isExpired }; });
      const batched = batches.reduce((sum, b) => sum + b.stockBaseQty, 0);
      const expired = batches.reduce((sum, b) => sum + (b.isExpired ? b.stockBaseQty : 0), 0);
      const available = Math.max(0, p.stockOnHandBaseQty - batched) + batches.reduce((sum, b) => sum + b.availableBaseQty, 0);
      const sumType = (type: StockMovementType) => p.stockMovements.filter((m) => m.movementType === type).reduce((sum, m) => sum + Math.abs(m.quantityBase), 0);
      return { productId: p.id, name: p.name, sku: p.sku, barcode: p.barcode, baseUnit: p.baseUnit.symbol, unitsPerPack: p.packings[0]?.unitsPerPack ?? 1, currentBaseQty: p.stockOnHandBaseQty, availableBaseQty: available, damagedBaseQty: sumType("DAMAGE"), expiredBaseQty: expired, expiredWrittenOffBaseQty: sumType("EXPIRY"), returnedBaseQty: sumType("SALES_RETURN"), openingBaseQty: sumType("OPENING_STOCK"), reorderLevelBaseQty: p.reorderLevelBaseQty, isLowStock: available <= p.reorderLevelBaseQty, batches };
    }).filter((p) => !lowOnly || p.isLowStock);
  }

  async options() { const stock = await this.stock(); return stock.map((p) => ({ id: p.productId, name: p.name, sku: p.sku, baseUnit: p.baseUnit, unitsPerPack: p.unitsPerPack, stockBaseQty: p.currentBaseQty, unbatchedStockBaseQty: Math.max(0, p.currentBaseQty - p.batches.reduce((sum, b) => sum + b.stockBaseQty, 0)), batches: p.batches })); }

  async movements(query: { productId?: string | undefined; userId?: string | undefined; type?: StockMovementType | undefined; from?: Date | undefined; to?: Date | undefined; page?: number | undefined }) {
    const page = query.page ?? 1; const pageSize = 100;
    const where = { ...(query.productId ? { productId: query.productId } : {}), ...(query.userId ? { createdById: query.userId } : {}), ...(query.type ? { movementType: query.type } : {}), ...((query.from || query.to) ? { createdAt: { ...(query.from ? { gte: query.from } : {}), ...(query.to ? { lte: query.to } : {}) } } : {}) };
    const [items, total] = await this.db.$transaction([this.db.stockMovement.findMany({ where, include: { product: { select: { name: true, sku: true } }, batch: { select: { batchNumber: true } }, createdBy: { select: { displayName: true, username: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), this.db.stockMovement.count({ where })]);
    return { movements: items, total, page, pageSize };
  }

  async userSummary() { const users = await this.db.user.findMany({ where: { deletedAt: null }, select: { id: true, displayName: true, username: true, stockMovements: { select: { quantityBase: true, createdAt: true } } } }); return users.map((u) => ({ id: u.id, displayName: u.displayName, username: u.username, movementCount: u.stockMovements.length, netBaseQty: u.stockMovements.reduce((s, m) => s + m.quantityBase, 0), lastChangedAt: u.stockMovements.reduce<Date | null>((latest, m) => !latest || m.createdAt > latest ? m.createdAt : latest, null) })); }

  private async packing(productId: string) { const p = await this.db.product.findFirst({ where: { id: productId, deletedAt: null }, include: { packings: { where: { isActive: true }, orderBy: { unitsPerPack: "desc" }, take: 1 } } }); if (!p) throw new HttpError(404, "PRODUCT_NOT_FOUND", "Product was not found."); return { product: p, unitsPerPack: p.packings[0]?.unitsPerPack ?? 1 }; }

  async adjust(input: InventoryAdjustmentInput, userId: string) { const { product, unitsPerPack } = await this.packing(input.productId); const qty = toBaseQuantity(input.packQuantity, input.baseQuantity, unitsPerPack); const reference = uid("ADJ"), quantityBase = input.movementType === "ADJUSTMENT_OUT" ? -qty : qty, unitCostMinor = product.averageCostMinor || product.purchasePriceMinor, valueMinor = qty * unitCostMinor; return this.db.$transaction(async (tx) => { const movement = await applyStockMovement(tx, { productId: input.productId, batchId: input.batchId, movementType: input.movementType, quantityBase, unitCostMinor, sourceType: "STOCK_ADJUSTMENT", sourceId: reference, sourceLineId: "1", notes: input.reason, createdById: userId }); if (valueMinor) await AccountingPostingService.post(tx, { sourceType: "STOCK_ADJUSTMENT", sourceId: reference, transactionDate: movement.createdAt, description: input.reason, createdById: userId, lines: input.movementType === "ADJUSTMENT_IN" ? [{ systemCode: "INVENTORY", debitMinor: valueMinor, productId: input.productId }, { systemCode: "OTHER_INCOME", creditMinor: valueMinor }] : [{ systemCode: "INVENTORY_LOSS", debitMinor: valueMinor }, { systemCode: "INVENTORY", creditMinor: valueMinor, productId: input.productId }] }); await tx.auditLog.create({ data: { userId, action: "POST", entityType: "StockAdjustment", entityId: reference, afterJson: JSON.stringify({ ...input, quantityBase, valueMinor }) } }); return movement; }); }

  async writeOff(input: InventoryWriteOffInput, userId: string) { const { product, unitsPerPack } = await this.packing(input.productId); const qty = toBaseQuantity(input.packQuantity, input.baseQuantity, unitsPerPack), unitCostMinor = product.averageCostMinor || product.purchasePriceMinor, costMinor = qty * unitCostMinor; const number = uid(input.type === "DAMAGE" ? "DMG" : input.type === "EXPIRY" ? "EXP" : input.type === "LEAKED" ? "LEK" : "MIS"); return this.db.$transaction(async (tx) => { const damageType = input.type === "DAMAGE" ? "DAMAGED" : input.type === "EXPIRY" ? "EXPIRED" : input.type; const movementType = input.type === "DAMAGE" || input.type === "LEAKED" ? "DAMAGE" : input.type === "EXPIRY" ? "EXPIRY" : "ADJUSTMENT_OUT"; const entry = await tx.damageEntry.create({ data: { entryNumber: number, type: damageType, productId: input.productId, batchId: input.batchId ?? null, quantityBase: qty, costMinor, reason: input.reason, createdById: userId } }); await applyStockMovement(tx, { productId: input.productId, batchId: input.batchId, movementType, quantityBase: -qty, unitCostMinor, sourceType: "DAMAGE_ENTRY", sourceId: entry.id, sourceLineId: "1", notes: input.reason, createdById: userId }); if (costMinor) await AccountingPostingService.post(tx, { sourceType: "DAMAGE_ENTRY", sourceId: entry.id, transactionDate: entry.occurredAt, description: `${damageType}: ${input.reason}`, createdById: userId, lines: [{ systemCode: "INVENTORY_LOSS", debitMinor: costMinor }, { systemCode: "INVENTORY", creditMinor: costMinor, productId: input.productId }] }); await tx.auditLog.create({ data: { userId, action: "POST", entityType: "DamageEntry", entityId: entry.id, afterJson: JSON.stringify({ ...input, quantityBase: qty, costMinor }) } }); return entry; }); }

  async cartonOpen(input: CartonOpenInput, userId: string) { const { product, unitsPerPack } = await this.packing(input.productId); const id = uid("CARTON"); const convertedBaseQty = toBaseQuantity(input.cartons, 0, unitsPerPack); if (product.stockOnHandBaseQty < convertedBaseQty) throw new HttpError(409, "INSUFFICIENT_CARTON_STOCK", "There is not enough stock to open this many cartons."); const movement = await this.db.$transaction((tx) => applyStockMovement(tx, { productId: input.productId, movementType: "CARTON_OPEN", quantityBase: 0, sourceType: "STOCK_ADJUSTMENT", sourceId: id, sourceLineId: "1", notes: input.notes ?? `${input.cartons} carton(s) opened into ${convertedBaseQty} base units.`, createdById: userId })); return { movement, convertedBaseQty }; }

  async physicalCount(input: StockCountInput, userId: string) {
    const keys = new Set(input.lines.map((l) => `${l.productId}:${l.batchId ?? ""}`)); if (keys.size !== input.lines.length) throw new HttpError(400, "DUPLICATE_COUNT_LINE", "A product and batch may only appear once per count.");
    return this.db.$transaction(async (tx) => { const count = await tx.stockCount.create({ data: { countNumber: uid("SC"), notes: input.notes ?? null, createdById: userId } });
      for (const line of input.lines) { const product = await tx.product.findFirst({ where: { id: line.productId, deletedAt: null }, include: { packings: { where: { isActive: true }, orderBy: { unitsPerPack: "desc" }, take: 1 }, batches: { select: { stockOnHandBaseQty: true } } } }); if (!product) throw new HttpError(404, "PRODUCT_NOT_FOUND", "Product was not found."); let expected = Math.max(0, product.stockOnHandBaseQty - product.batches.reduce((sum, batch) => sum + batch.stockOnHandBaseQty, 0)); if (line.batchId) { const batch = await tx.productBatch.findFirst({ where: { id: line.batchId, productId: line.productId } }); if (!batch) throw new HttpError(400, "INVALID_BATCH", "Batch does not belong to this product."); expected = batch.stockOnHandBaseQty; }
        const counted = toBaseQuantity(line.countedPackQuantity, line.countedBaseQuantity, product.packings[0]?.unitsPerPack ?? 1); const variance = counted - expected; const item = await tx.stockCountItem.create({ data: { stockCountId: count.id, productId: line.productId, batchId: line.batchId ?? null, expectedBaseQty: expected, countedBaseQty: counted, varianceBaseQty: variance } }); if (variance) { const unitCostMinor = product.averageCostMinor || product.purchasePriceMinor, valueMinor = Math.abs(variance) * unitCostMinor; const movement = await applyStockMovement(tx, { productId: line.productId, batchId: line.batchId, movementType: variance > 0 ? "ADJUSTMENT_IN" : "ADJUSTMENT_OUT", quantityBase: variance, unitCostMinor, sourceType: "PHYSICAL_COUNT", sourceId: count.id, sourceLineId: item.id, notes: `Physical count ${count.countNumber}`, createdById: userId }); if (valueMinor) await AccountingPostingService.post(tx, { sourceType: "PHYSICAL_COUNT", sourceId: count.id, postingKey: item.id, transactionDate: movement.createdAt, description: `Physical count ${count.countNumber}`, createdById: userId, lines: variance > 0 ? [{ systemCode: "INVENTORY", debitMinor: valueMinor, productId: line.productId }, { systemCode: "OTHER_INCOME", creditMinor: valueMinor }] : [{ systemCode: "INVENTORY_LOSS", debitMinor: valueMinor }, { systemCode: "INVENTORY", creditMinor: valueMinor, productId: line.productId }] }); } }
      await tx.auditLog.create({ data: { userId, action: "POST", entityType: "StockCount", entityId: count.id, afterJson: JSON.stringify({ countNumber: count.countNumber, lineCount: input.lines.length }) } });
      return tx.stockCount.findUnique({ where: { id: count.id }, include: { items: true } }); });
  }

  async counts() { return this.db.stockCount.findMany({ include: { createdBy: { select: { displayName: true } }, items: { include: { product: { select: { name: true, sku: true } }, batch: { select: { batchNumber: true } } } } }, orderBy: { countedAt: "desc" }, take: 100 }); }
}
