import { brandFooter, brandHeader, brandingCss, currentBusiness, escapeHtml as escape } from "@/features/printing/brand";

export type ReturnReceipt = { returnNumber: string; returnedAt: string; reason: string; refundMethod: string; returnTotal: string; replacementTotal: string; refund: string; sale: { invoiceNumber: string }; customer: { name: string; businessName: string | null } | null; createdBy: { displayName: string }; items: Array<{ id: string; quantityBase: number; condition: string; lineTotal: string; product: { name: string; sku: string; baseUnit: { symbol: string } }; batch: { batchNumber: string } | null }>; replacementItems: Array<{ id: string; quantityBase: number; lineTotal: string; product: { name: string; sku: string; baseUnit: { symbol: string } }; batch: { batchNumber: string } | null }> };

export function salesReturnReceiptHtml(value: ReturnReceipt, reprint = false) {
  const business = currentBusiness();
  const returned = value.items.map((item) => `<tr><td>${escape(item.product.name)}<br><small>${escape(item.product.sku)} · ${escape(item.batch?.batchNumber ?? "No batch")}</small></td><td>${escape(item.quantityBase)} ${escape(item.product.baseUnit.symbol)}</td><td>${escape(item.condition)}</td><td class="right">${escape(item.lineTotal)}</td></tr>`).join("");
  const replacements = value.replacementItems.map((item) => `<tr><td>${escape(item.product.name)}</td><td>${escape(item.quantityBase)} ${escape(item.product.baseUnit.symbol)}</td><td class="right">${escape(item.lineTotal)}</td></tr>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:7mm}${brandingCss}body{font:12px Arial;color:#111}h1,.document-meta{text-align:center}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{padding:6px 3px;border-bottom:1px dashed #bbb;text-align:left}.right{text-align:right}.row{display:flex;justify-content:space-between;padding:4px 0}.total{font-size:15px;font-weight:bold}</style></head><body>${brandHeader(business)}<h1>Sales return</h1><p class="document-meta">${escape(value.returnNumber)}<br>${escape(new Date(value.returnedAt).toLocaleString("en-PK", { timeZone: business.timezone }))}</p><div class="row"><span>Original invoice</span><b>${escape(value.sale.invoiceNumber)}</b></div><div class="row"><span>Customer</span><span>${escape(value.customer?.businessName ?? value.customer?.name ?? "Walk-in customer")}</span></div><table><thead><tr><th>Returned item</th><th>Qty</th><th>Condition</th><th class="right">Value</th></tr></thead><tbody>${returned}</tbody></table>${replacements ? `<h3>Replacement issued</h3><table><tbody>${replacements}</tbody></table>` : ""}<div class="row"><span>Returned value</span><b>${escape(business.currency)} ${escape(value.returnTotal)}</b></div><div class="row"><span>Replacement value</span><span>${escape(business.currency)} ${escape(value.replacementTotal)}</span></div><div class="row total"><span>${value.refundMethod === "CASH" ? "Cash refund" : "Khata adjustment"}</span><span>${escape(business.currency)} ${escape(value.refund)}</span></div><p><b>Reason:</b> ${escape(value.reason)}</p><p>Processed by ${escape(value.createdBy.displayName)}</p>${brandFooter(business)}</body></html>`;
}

export async function printSalesReturn(value: ReturnReceipt, format: "THERMAL" | "PDF", reprint = false) {
  const html = salesReturnReceiptHtml(value, reprint);
  if (format === "THERMAL") { if (!window.agencyDesktop?.printThermal) throw new Error("Thermal printing is available only in the desktop app."); return window.agencyDesktop.printThermal(html); }
  if (!window.agencyDesktop?.printPdf) throw new Error("PDF printing is available only in the desktop app.");
  return window.agencyDesktop.printPdf(html, `sales-return-${value.returnNumber}`);
}
