import { brandFooter, brandHeader, brandingCss, currentBusiness, escapeHtml as e } from "@/features/printing/brand";

export async function printSupplierStatement(s: { supplier: { name: string; businessName: string | null; code: string }; previousBalance: string; currentBalance: string; overdue: string; entries: Array<{ occurredAt: string; entryType: string; notes: string | null; debit: string; credit: string; currentBalance: string }> }) {
  const business = currentBusiness();
  const rows = s.entries.map((x) => `<tr><td>${e(new Date(x.occurredAt).toLocaleDateString("en-PK", { timeZone: business.timezone }))}</td><td>${e(x.entryType)}</td><td>${e(x.notes ?? "")}</td><td>${e(x.debit)}</td><td>${e(x.credit)}</td><td>${e(x.currentBalance)}</td></tr>`).join("");
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:10mm}${brandingCss}body{font:12px Arial;color:#111}h1{text-align:center}table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid #ddd;text-align:right}th:first-child,td:first-child,th:nth-child(2),td:nth-child(2),th:nth-child(3),td:nth-child(3){text-align:left}.summary{margin:20px 0 0 auto;width:300px}.row{display:flex;justify-content:space-between;padding:4px}.total{font-size:16px;font-weight:bold}</style></head><body>${brandHeader(business)}<h1>Supplier statement</h1><p><b>${e(s.supplier.name)}</b> ${e(s.supplier.businessName ?? "")} · ${e(s.supplier.code)}</p><table><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Debit</th><th>Credit</th><th>Payable</th></tr></thead><tbody>${rows}</tbody></table><div class="summary"><div class="row"><span>Previous payable</span><span>${e(business.currency)} ${e(s.previousBalance)}</span></div><div class="row total"><span>Current payable</span><span>${e(business.currency)} ${e(s.currentBalance)}</span></div><div class="row"><span>Overdue</span><span>${e(business.currency)} ${e(s.overdue)}</span></div></div>${brandFooter(business)}</body></html>`;
  if (!window.agencyDesktop?.printPdf) throw new Error("Printing is only available in the desktop app.");
  return window.agencyDesktop.printPdf(html, `supplier-${s.supplier.code}`);
}
