import { Prisma, type CashDirection, type CashbookEntryType, type PrismaClient } from "@prisma/client";
import type { CashbookReportQuery, CreateCashbookEntryInput, DailyClosingInput } from "@oil-agency/shared";
import { HttpError } from "../../lib/http-error.js";
import { moneyToMinor, minorToMoney } from "../products/product.service.js";
import { AccountingPostingService, type PostingLine, type SystemAccountCode } from "../accounting/posting.service.js";
import { pakistanDay } from "../../lib/business-time.js";

const reference = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
export { pakistanDay };
export function cashTotals(entries: Array<{ direction: CashDirection; entryType: CashbookEntryType; amountMinor: number }>) { const openingCashMinor = entries.filter((entry) => entry.entryType === "OPENING_CASH").reduce((sum, entry) => sum + entry.amountMinor, 0); const cashInMinor = entries.filter((entry) => entry.direction === "IN" && entry.entryType !== "OPENING_CASH").reduce((sum, entry) => sum + entry.amountMinor, 0); const cashOutMinor = entries.filter((entry) => entry.direction === "OUT").reduce((sum, entry) => sum + entry.amountMinor, 0); return { openingCashMinor, cashInMinor, cashOutMinor, expectedCashMinor: openingCashMinor + cashInMinor - cashOutMinor }; }
export function cashDifference(expectedCashMinor: number, countedCashMinor: number) { if (![expectedCashMinor, countedCashMinor].every(Number.isSafeInteger)) throw new HttpError(400, "INVALID_CASH_TOTAL", "Cash totals are invalid."); return countedCashMinor - expectedCashMinor; }

const entryInclude = { createdBy: { select: { id: true, displayName: true, username: true } }, payment: { select: { receiptNumber: true, sale: { select: { invoiceNumber: true } }, purchase: { select: { invoiceNumber: true } }, customer: { select: { name: true, businessName: true } }, supplier: { select: { name: true, businessName: true } } } }, salesReturn: { select: { returnNumber: true, sale: { select: { invoiceNumber: true } } } }, expense: { select: { voucherNumber: true, category: true } } } satisfies Prisma.CashbookEntryInclude;
type EntryRecord = Prisma.CashbookEntryGetPayload<{ include: typeof entryInclude }>;
const displayType = (type: CashbookEntryType) => ({ SALE_RECEIPT: "CASH_SALE", CUSTOMER_RECEIPT: "CUSTOMER_RECOVERY", PURCHASE_PAYMENT: "SUPPLIER_PAYMENT" } as Partial<Record<CashbookEntryType, string>>)[type] ?? type;

export class CashbookService {
  constructor(private readonly db: PrismaClient) {}

  async users() { return this.db.user.findMany({ where: { cashbookEntries: { some: {} } }, select: { id: true, displayName: true, username: true }, orderBy: { displayName: "asc" } }); }

  async report(query: CashbookReportQuery) {
    const range = { gte: pakistanDay(query.from).start, lte: pakistanDay(query.to).end };
    const [entries, closings] = await Promise.all([
      this.db.cashbookEntry.findMany({ where: { occurredAt: range, ...(query.userId ? { createdById: query.userId } : {}), ...(query.paymentMethod ? { payment: { method: query.paymentMethod } } : {}) }, include: entryInclude, orderBy: [{ occurredAt: "asc" }, { createdAt: "asc" }] }),
      this.db.dailyClosing.findMany({ where: { businessDate: { gte: pakistanDay(query.from).businessDate, lte: pakistanDay(query.to).businessDate }, ...(query.userId ? { closedById: query.userId } : {}) }, include: { closedBy: { select: { id: true, displayName: true, username: true } } }, orderBy: { businessDate: "desc" } }),
    ]);
    const totals = cashTotals(entries); let runningMinor = 0;
    return { entries: entries.map((entry) => { runningMinor += entry.direction === "IN" ? entry.amountMinor : -entry.amountMinor; return entryDto(entry, runningMinor); }), summary: { openingCash: minorToMoney(totals.openingCashMinor), cashIn: minorToMoney(totals.cashInMinor), cashOut: minorToMoney(totals.cashOutMinor), expectedCash: minorToMoney(totals.expectedCashMinor) }, closings: closings.map((closing) => ({ ...closing, businessDate: closing.businessDate.toISOString().slice(0, 10), openingCash: minorToMoney(closing.openingCashMinor), cashIn: minorToMoney(closing.cashInMinor), cashOut: minorToMoney(closing.cashOutMinor), expectedCash: minorToMoney(closing.expectedCashMinor), countedCash: minorToMoney(closing.countedCashMinor), difference: minorToMoney(closing.differenceMinor) })) };
  }

  async daySummary(date: string) { const day = pakistanDay(date); const entries = await this.db.cashbookEntry.findMany({ where: { occurredAt: { gte: day.start, lte: day.end } }, select: { direction: true, entryType: true, amountMinor: true } }); const totals = cashTotals(entries); const closing = await this.db.dailyClosing.findUnique({ where: { businessDate: day.businessDate }, include: { closedBy: { select: { displayName: true } } } }); return { businessDate: date, openingCash: minorToMoney(totals.openingCashMinor), cashIn: minorToMoney(totals.cashInMinor), cashOut: minorToMoney(totals.cashOutMinor), expectedCash: minorToMoney(totals.expectedCashMinor), closed: Boolean(closing), closing: closing ? { id: closing.id, countedCash: minorToMoney(closing.countedCashMinor), difference: minorToMoney(closing.differenceMinor), notes: closing.notes, closedAt: closing.closedAt, closedBy: closing.closedBy } : null }; }

  async createEntry(input: CreateCashbookEntryInput, userId: string) { const amountMinor = moneyToMinor(input.amount); if (amountMinor <= 0) throw new HttpError(400, "INVALID_AMOUNT", "Cash amount must be greater than zero."); const day = pakistanDay(input.occurredOn); return this.db.$transaction(async (tx) => { if (await tx.dailyClosing.findUnique({ where: { businessDate: day.businessDate } })) throw new HttpError(409, "DAY_ALREADY_CLOSED", "Cash entries cannot be posted after the day is closed."); if (input.entryType === "OPENING_CASH" && await tx.cashbookEntry.findFirst({ where: { entryType: "OPENING_CASH", occurredAt: { gte: day.start, lte: day.end } } })) throw new HttpError(409, "OPENING_CASH_EXISTS", "Opening cash has already been entered for this date."); const sourceId = reference("CB"); const entry = await tx.cashbookEntry.create({ data: { entryNumber: reference("CASH"), direction: input.direction, entryType: input.entryType, amountMinor, sourceType: "CASHBOOK", sourceId, reference: input.reference ?? null, notes: input.notes, occurredAt: day.businessDate, createdById: userId }, include: entryInclude }); const counterpart = cashbookCounterpart(input.entryType); const lines: PostingLine[] = input.direction === "IN" ? [{ systemCode: "CASH", debitMinor: amountMinor }, { systemCode: counterpart, creditMinor: amountMinor }] : [{ systemCode: counterpart, debitMinor: amountMinor }, { systemCode: "CASH", creditMinor: amountMinor }]; await AccountingPostingService.post(tx, { sourceType: "CASHBOOK", sourceId, transactionDate: day.businessDate, description: input.notes || input.entryType, createdById: userId, lines }); await tx.auditLog.create({ data: { userId, action: "POST", entityType: "CashbookEntry", entityId: entry.id, afterJson: JSON.stringify({ entryNumber: entry.entryNumber, entryType: entry.entryType, direction: entry.direction, amountMinor, occurredOn: input.occurredOn, reference: input.reference ?? null }) } }); return entryDto(entry, null); }); }

  async close(input: DailyClosingInput, userId: string) { const countedCashMinor = moneyToMinor(input.countedCash); if (countedCashMinor < 0) throw new HttpError(400, "INVALID_COUNTED_CASH", "Actual cash cannot be negative."); const day = pakistanDay(input.businessDate); return this.db.$transaction(async (tx) => { if (await tx.dailyClosing.findUnique({ where: { businessDate: day.businessDate } })) throw new HttpError(409, "DAY_ALREADY_CLOSED", "This business date has already been closed."); const entries = await tx.cashbookEntry.findMany({ where: { occurredAt: { gte: day.start, lte: day.end } }, select: { direction: true, entryType: true, amountMinor: true } }); const totals = cashTotals(entries); const differenceMinor = cashDifference(totals.expectedCashMinor, countedCashMinor); const closing = await tx.dailyClosing.create({ data: { businessDate: day.businessDate, ...totals, countedCashMinor, differenceMinor, notes: input.notes ?? null, closedById: userId }, include: { closedBy: { select: { displayName: true, username: true } } } }); if (differenceMinor !== 0) { const amountMinor = Math.abs(differenceMinor); await tx.cashbookEntry.create({ data: { entryNumber: reference("CASH"), direction: differenceMinor > 0 ? "IN" : "OUT", entryType: "CLOSING_ADJUSTMENT", amountMinor, sourceType: "DAILY_CLOSING", sourceId: closing.id, notes: `Cash ${differenceMinor > 0 ? "over" : "short"} at daily closing`, occurredAt: day.businessDate, createdById: userId } }); await AccountingPostingService.post(tx, { sourceType: "DAILY_CLOSING", sourceId: closing.id, transactionDate: day.businessDate, description: `Cash difference ${input.businessDate}`, createdById: userId, lines: differenceMinor > 0 ? [{ systemCode: "CASH", debitMinor: amountMinor }, { systemCode: "CASH_OVER_SHORT", creditMinor: amountMinor }] : [{ systemCode: "CASH_OVER_SHORT", debitMinor: amountMinor }, { systemCode: "CASH", creditMinor: amountMinor }] }); } await tx.auditLog.create({ data: { userId, action: "CLOSE", entityType: "DailyClosing", entityId: closing.id, afterJson: JSON.stringify({ businessDate: input.businessDate, ...totals, countedCashMinor, differenceMinor }) } }); return { ...closing, businessDate: input.businessDate, openingCash: minorToMoney(closing.openingCashMinor), cashIn: minorToMoney(closing.cashInMinor), cashOut: minorToMoney(closing.cashOutMinor), expectedCash: minorToMoney(closing.expectedCashMinor), countedCash: minorToMoney(closing.countedCashMinor), difference: minorToMoney(closing.differenceMinor) }; }); }

  async closeAutomatically(businessDate: string, userId: string) { const day = pakistanDay(businessDate); return this.db.$transaction(async (tx) => { const existing = await tx.dailyClosing.findUnique({ where: { businessDate: day.businessDate } }); if (existing) return { created: false as const, closing: existing }; const entries = await tx.cashbookEntry.findMany({ where: { occurredAt: { gte: day.start, lte: day.end } }, select: { direction: true, entryType: true, amountMinor: true } }); const totals = cashTotals(entries); const closing = await tx.dailyClosing.create({ data: { businessDate: day.businessDate, ...totals, countedCashMinor: totals.expectedCashMinor, differenceMinor: 0, notes: "Automatically closed at 8:00 PM Asia/Karachi; counted cash set to system expected cash.", closedById: userId } }); await tx.auditLog.create({ data: { userId, action: "CLOSE", entityType: "DailyClosing", entityId: closing.id, afterJson: JSON.stringify({ businessDate, ...totals, countedCashMinor: totals.expectedCashMinor, differenceMinor: 0, automatic: true, timezone: "Asia/Karachi", scheduledHour: 20 }) } }); return { created: true as const, closing }; }); }
}

function entryDto(entry: EntryRecord, runningMinor: number | null) { const transactionReference = entry.payment ? { type: "PAYMENT", number: entry.payment.receiptNumber, documentNumber: entry.payment.sale?.invoiceNumber ?? entry.payment.purchase?.invoiceNumber ?? null, party: entry.payment.customer?.businessName ?? entry.payment.customer?.name ?? entry.payment.supplier?.businessName ?? entry.payment.supplier?.name ?? null } : entry.salesReturn ? { type: "SALES_RETURN", number: entry.salesReturn.returnNumber, documentNumber: entry.salesReturn.sale.invoiceNumber, party: null } : entry.expense ? { type: "EXPENSE", number: entry.expense.voucherNumber, documentNumber: null, party: entry.expense.category } : null; return { ...entry, entryType: displayType(entry.entryType), amount: minorToMoney(entry.amountMinor), runningBalance: runningMinor === null ? null : minorToMoney(runningMinor), transactionReference }; }
function cashbookCounterpart(type: CashbookEntryType): SystemAccountCode { if (type === "OPENING_CASH") return "OPENING_EQUITY"; if (type === "OWNER_INVESTMENT") return "CAPITAL"; if (type === "OWNER_WITHDRAWAL") return "DRAWINGS"; if (type === "CASH_DEPOSIT" || type === "CASH_WITHDRAWAL") return "BANK_CLEARING"; if (type === "OTHER_INCOME") return "OTHER_INCOME"; if (type === "CLOSING_ADJUSTMENT") return "CASH_OVER_SHORT"; return "EXPENSE_GENERAL"; }
