import { brandFooter, brandHeader, brandingCss, currentBusiness, escapeHtml } from "@/features/printing/brand";
import writeXlsxFile from "write-excel-file";

export type ReportCell = string | number | boolean | null | undefined;
export type ReportSection = { title: string; columns: Array<{ key: string; label: string }>; rows: Array<Record<string, ReportCell>> };
export type ReportDetail = { label: string; value: ReportCell };
const csvCell = (value: ReportCell) => `"${String(value ?? "").replaceAll('"', '""')}"`;
export function exportReportCsv(title: string, sections: ReportSection[]) { const lines = sections.flatMap((section) => [[csvCell(section.title)], section.columns.map((column) => csvCell(column.label)), ...section.rows.map((row) => section.columns.map((column) => csvCell(row[column.key]))), []]).map((row) => row.join(",")); const blob = new Blob(["\uFEFF", lines.join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.csv`; anchor.click(); URL.revokeObjectURL(url); }
export async function exportReportXlsx(title: string, sections: ReportSection[]) { const sheets = sections.map((section) => [section.columns.map((column) => ({ value: column.label, fontWeight: "bold" as const, backgroundColor: "#198754", color: "#FFFFFF" })), ...section.rows.map((row) => section.columns.map((column) => { const value = row[column.key]; return { value: value == null ? "" : value, type: typeof value === "number" ? Number : typeof value === "boolean" ? Boolean : String }; }))]); await writeXlsxFile(sheets, { sheets: sections.map((section, index) => `${index + 1}-${section.title}`.replace(/[\\/?*\[\]:]/g, " ").slice(0, 31)), fileName: `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.xlsx` }); }
export function reportHtml(title: string, subtitle: string, sections: ReportSection[], details: ReportDetail[] = [], summary: Record<string, ReportCell> = {}) { const business = currentBusiness(); const detailBlock = details.length ? `<section class="party-details">${details.filter((detail) => detail.value != null && detail.value !== "").map((detail) => `<div><span>${escapeHtml(detail.label)}</span><b>${escapeHtml(detail.value)}</b></div>`).join("")}</section>` : ""; const summaryBlock = Object.keys(summary).length ? `<section class="summary">${Object.entries(summary).map(([key, value]) => `<div><span>${escapeHtml(key)}</span><b>${escapeHtml(value)}</b></div>`).join("")}</section>` : ""; const body = sections.map((section) => `<h2>${escapeHtml(section.title)}</h2><table><thead><tr>${section.columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("")}</tr></thead><tbody>${section.rows.map((row) => `<tr>${section.columns.map((column) => `<td>${escapeHtml(row[column.key])}</td>`).join("")}</tr>`).join("")}</tbody></table>`).join(""); return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4 landscape;margin:10mm 9mm 13mm;@bottom-center{content:"Page " counter(page) " of " counter(pages);font:9px Arial;color:#555}}${brandingCss}.agency-brand{justify-content:flex-start;text-align:left}.agency-logo{width:48px;height:48px}body{font:10px Arial;color:#111}h1{margin:0;text-align:center}.report-subtitle{text-align:center;color:#555}.party-details,.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border:1px solid #bbb;margin:12px 0 16px;page-break-inside:avoid}.party-details div,.summary div{display:flex;gap:8px;padding:6px 8px;border-right:1px solid #ddd;border-bottom:1px solid #ddd}.party-details span,.summary span{color:#555;min-width:70px}.party-details b{overflow-wrap:anywhere}h2{margin:18px 0 6px;font-size:14px}table{width:100%;border-collapse:collapse;page-break-inside:auto}thead{display:table-header-group}th,td{padding:5px;border:1px solid #ccc;text-align:left}th{background:#eee}tr{page-break-inside:avoid}</style></head><body>${brandHeader(business)}<h1>${escapeHtml(title)}</h1><p class="report-subtitle">${escapeHtml(subtitle)}</p>${detailBlock}${summaryBlock}${body}${brandFooter(business)}</body></html>`; }
export async function printReport(title: string, subtitle: string, sections: ReportSection[], details: ReportDetail[] = [], summary: Record<string, ReportCell> = {}) { if (!window.agencyDesktop?.printReport) throw new Error("Printing is available in the desktop app."); return window.agencyDesktop.printReport(reportHtml(title, subtitle, sections, details, summary)); }
export async function exportReportPdf(title: string, subtitle: string, sections: ReportSection[], details: ReportDetail[] = [], summary: Record<string, ReportCell> = {}) { if (!window.agencyDesktop?.printPdf) throw new Error("PDF export is available in the desktop app."); return window.agencyDesktop.printPdf(reportHtml(title, subtitle, sections, details, summary), title); }
