import { ChevronDown, ChevronLeft, ChevronRight, Columns3, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { ReportCell, ReportSection } from "./export-helpers";

const PAGE_SIZES = [10, 25, 50, 100];
const numeric = (value: ReportCell) => typeof value === "number" || (typeof value === "string" && value.trim() !== "" && Number.isFinite(Number(value)));

export function ReportTable({ section, onRow }: { section: ReportSection; onRow?(row: Record<string, ReportCell>): void }) {
  const [search, setSearch] = useState(""); const [columnFilters, setColumnFilters] = useState<Record<string, string>>({}); const [sortKey, setSortKey] = useState(""); const [descending, setDescending] = useState(false); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25); const [visible, setVisible] = useState(() => new Set(section.columns.map((column) => column.key))); const [columnsOpen, setColumnsOpen] = useState(false);
  const columns = section.columns.filter((column) => visible.has(column.key));
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase(); const rows = section.rows.filter((row) => (!term || section.columns.some((column) => String(row[column.key] ?? "").toLocaleLowerCase().includes(term))) && Object.entries(columnFilters).every(([key, value]) => !value || String(row[key] ?? "").toLocaleLowerCase().includes(value.toLocaleLowerCase()))); if (sortKey) rows.sort((left, right) => { const a = left[sortKey], b = right[sortKey]; const result = numeric(a) && numeric(b) ? Number(a) - Number(b) : String(a ?? "").localeCompare(String(b ?? ""), undefined, { numeric: true }); return descending ? -result : result; }); return rows; }, [section, search, columnFilters, sortKey, descending]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(page, pageCount); const rows = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const totals = Object.fromEntries(columns.map((column) => { const values = filtered.map((row) => row[column.key]); return [column.key, values.length > 0 && values.every((value) => value == null || value === "" || numeric(value)) ? values.reduce<number>((sum, value) => sum + (value == null || value === "" ? 0 : Number(value)), 0) : null]; }));
  function sort(key: string) { if (sortKey === key) setDescending((value) => !value); else { setSortKey(key); setDescending(false); } }
  return <div>
    <div className="flex flex-wrap items-center gap-2 border-b bg-slate-50/70 p-3">
      <div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-muted-foreground" size={16}/><Input className="bg-white pl-9" value={search} placeholder={`Search ${section.title.toLowerCase()}…`} onChange={(event) => { setSearch(event.target.value); setPage(1); }}/></div>
      <div className="relative"><Button variant="outline" onClick={() => setColumnsOpen((value) => !value)}><Columns3 className="mr-2" size={16}/>Columns<ChevronDown className="ml-2" size={14}/></Button>{columnsOpen && <div className="absolute right-0 z-20 mt-1 min-w-52 rounded-lg border bg-white p-2 shadow-xl">{section.columns.map((column) => <label key={column.key} className="flex cursor-pointer gap-2 rounded px-2 py-1.5 text-sm hover:bg-slate-50"><input type="checkbox" checked={visible.has(column.key)} onChange={() => setVisible((current) => { const next = new Set(current); if (next.has(column.key) && next.size > 1) next.delete(column.key); else next.add(column.key); return next; })}/>{column.label}</label>)}</div>}</div>
      <select className="h-10 rounded-lg border bg-white px-3 text-sm" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }}>{PAGE_SIZES.map((size) => <option key={size} value={size}>{size} rows</option>)}</select>
    </div>
    <div className="max-h-[560px] overflow-auto"><Table><TableHeader className="sticky top-0 z-10 bg-slate-100"><TableRow>{columns.map((column) => <TableHead key={column.key}><button className="flex w-full items-center gap-1 text-left" onClick={() => sort(column.key)}>{column.label}{sortKey === column.key && <span>{descending ? "↓" : "↑"}</span>}</button></TableHead>)}</TableRow><TableRow>{columns.map((column) => <TableHead key={column.key} className="bg-white p-1"><input className="h-7 w-full min-w-20 rounded border px-2 text-xs font-normal" value={columnFilters[column.key] ?? ""} placeholder="Filter…" aria-label={`Filter ${column.label}`} onChange={(event) => { setColumnFilters((current) => ({ ...current, [column.key]: event.target.value })); setPage(1); }}/></TableHead>)}</TableRow></TableHeader><TableBody>{rows.length ? rows.map((row, index) => <TableRow key={`${currentPage}-${index}`} className={onRow ? "cursor-pointer hover:bg-emerald-50/50" : ""} onClick={() => onRow?.(row)}>{columns.map((column) => <TableCell key={column.key}>{String(row[column.key] ?? "—")}</TableCell>)}</TableRow>) : <TableRow><TableCell colSpan={columns.length} className="py-12 text-center text-muted-foreground">No records match the current filters.</TableCell></TableRow>}{filtered.length > 0 && <TableRow className="sticky bottom-0 bg-slate-100 font-bold">{columns.map((column, index) => <TableCell key={column.key}>{index === 0 ? `Total (${filtered.length})` : totals[column.key] == null ? "" : Number(totals[column.key]).toFixed(2)}</TableCell>)}</TableRow>}</TableBody></Table></div>
    <div className="flex items-center justify-between border-t p-3 text-sm"><span className="text-muted-foreground">{filtered.length ? `${(currentPage - 1) * pageSize + 1}–${Math.min(currentPage * pageSize, filtered.length)} of ${filtered.length}` : "0 records"}</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={currentPage <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft size={16}/></Button><span>Page {currentPage} of {pageCount}</span><Button size="sm" variant="outline" disabled={currentPage >= pageCount} onClick={() => setPage((value) => value + 1)}><ChevronRight size={16}/></Button></div></div>
  </div>;
}
