import { useMemo, useState } from "react";
import type { ReportSection } from "./export-helpers";

type ChartType = "BAR" | "LINE" | "AREA" | "PIE";
const colors = ["#198754", "#0f766e", "#2563eb", "#d97706", "#dc2626", "#7c3aed", "#0891b2", "#65a30d"];

export function ReportChart({ section }: { section: ReportSection }) {
  const numericColumns = section.columns.filter((column) => section.rows.some((row) => Number.isFinite(Number(row[column.key])))); const labelColumn = section.columns.find((column) => !numericColumns.includes(column)); const [type, setType] = useState<ChartType>("BAR"); const [valueKey, setValueKey] = useState(numericColumns[0]?.key ?? "");
  const data = useMemo(() => section.rows.slice(0, 20).map((row, index) => ({ label: String(row[labelColumn?.key ?? section.columns[0]?.key ?? ""] ?? index + 1), value: Number(row[valueKey]) || 0 })).filter((row) => Number.isFinite(row.value)), [section, labelColumn, valueKey]);
  if (!valueKey || data.length < 2) return null; const max = Math.max(...data.map((row) => Math.abs(row.value)), 1); const points = data.map((row, index) => `${20 + index * (760 / Math.max(1, data.length - 1))},${190 - Math.abs(row.value) / max * 150}`).join(" ");
  return <div className="mb-5 rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h3 className="m-0 text-base">Visualization</h3><p className="m-0 mt-1 text-xs text-muted-foreground">Top 20 rows; updates with report filters</p></div><div className="flex gap-2"><select className="h-9 rounded-lg border px-2 text-sm" value={valueKey} onChange={(event) => setValueKey(event.target.value)}>{numericColumns.map((column) => <option key={column.key} value={column.key}>{column.label}</option>)}</select><select className="h-9 rounded-lg border px-2 text-sm" value={type} onChange={(event) => setType(event.target.value as ChartType)}><option value="BAR">Bar</option><option value="LINE">Line</option><option value="AREA">Area</option><option value="PIE">Pie</option></select></div></div>
    {type === "PIE" ? <div className="grid grid-cols-[180px_1fr] items-center gap-6"><div className="mx-auto h-40 w-40 rounded-full" style={{ background: `conic-gradient(${data.map((row, index) => { const total = data.reduce((sum, item) => sum + Math.abs(item.value), 0) || 1; const before = data.slice(0, index).reduce((sum, item) => sum + Math.abs(item.value), 0) / total * 100; const after = before + Math.abs(row.value) / total * 100; return `${colors[index % colors.length]} ${before}% ${after}%`; }).join(",")})` }}/><div className="grid grid-cols-2 gap-2">{data.slice(0, 8).map((row, index) => <div key={`${row.label}-${index}`} className="flex items-center gap-2 text-xs"><span className="h-3 w-3 rounded-sm" style={{ background: colors[index % colors.length] }}/><span className="truncate">{row.label}: {row.value.toFixed(2)}</span></div>)}</div></div> : type === "BAR" ? <div className="flex h-52 items-end gap-2 overflow-hidden border-b border-l px-3 pt-3">{data.map((row, index) => <div key={`${row.label}-${index}`} className="group flex min-w-0 flex-1 flex-col items-center justify-end" title={`${row.label}: ${row.value}`}><span className="mb-1 text-[9px] opacity-0 group-hover:opacity-100">{row.value.toFixed(0)}</span><div className="w-full min-w-2 rounded-t bg-primary/80" style={{ height: `${Math.max(2, Math.abs(row.value) / max * 160)}px` }}/><span className="mt-1 w-full truncate text-center text-[9px]">{row.label}</span></div>)}</div> : <svg viewBox="0 0 800 210" className="h-52 w-full rounded border bg-slate-50"><line x1="20" y1="190" x2="780" y2="190" stroke="#cbd5e1"/>{type === "AREA" && <polygon points={`20,190 ${points} 780,190`} fill="#19875422"/>}<polyline points={points} fill="none" stroke="#198754" strokeWidth="3"/>{data.map((row, index) => <circle key={index} cx={20 + index * (760 / Math.max(1, data.length - 1))} cy={190 - Math.abs(row.value) / max * 150} r="4" fill="#198754"><title>{row.label}: {row.value}</title></circle>)}</svg>}
  </div>;
}
