import type { Prisma, PrismaClient } from "@prisma/client";
import type { InventoryReportFilter, LedgerReportFilter, ReportDateFilter } from "@oil-agency/shared";
import { minorToMoney } from "../products/product.service.js";
import { pakistanDay } from "../cashbook/cashbook.service.js";

const dayKey = (date: Date) => { const parts = Object.fromEntries(new Intl.DateTimeFormat("en", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; };
const range = (from: string, to: string) => ({ gte: pakistanDay(from).start, lte: pakistanDay(to).end });
const add = <T>(map: Map<string, T>, key: string, initial: () => T) => { let row = map.get(key); if (!row) { row = initial(); map.set(key, row); } return row; };
export function classifySaleSettlement(paymentStatus: "PAID" | "PARTIAL" | "UNPAID", totalMinor: number, cashPaidMinor: number) { return paymentStatus === "UNPAID" ? "CREDIT" : paymentStatus === "PARTIAL" ? "PARTIAL" : cashPaidMinor >= totalMinor ? "CASH" : "PAID_NON_CASH"; }

export class ReportService {
  constructor(private readonly db: PrismaClient) {}
  async options() { const [customers, suppliers, products, categories] = await Promise.all([this.db.customer.findMany({ where: { deletedAt: null }, select: { id: true, name: true, businessName: true }, orderBy: { name: "asc" } }), this.db.supplier.findMany({ where: { deletedAt: null }, select: { id: true, name: true, businessName: true }, orderBy: { name: "asc" } }), this.db.product.findMany({ where: { deletedAt: null }, select: { id: true, name: true, sku: true, categoryId: true }, orderBy: { name: "asc" } }), this.db.category.findMany({ where: { deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); return { customers, suppliers, products, categories }; }

  async sales(filter: ReportDateFilter) {
    const itemWhere: Prisma.SaleItemWhereInput = { ...(filter.productId ? { productId: filter.productId } : {}), ...(filter.categoryId ? { product: { categoryId: filter.categoryId } } : {}) };
    const sales = await this.db.sale.findMany({ where: { status: "POSTED", soldAt: range(filter.from, filter.to), ...(filter.customerId ? { customerId: filter.customerId } : {}), ...(filter.paymentStatus ? { paymentStatus: filter.paymentStatus } : {}), ...(filter.paymentMethod ? { payments: { some: { method: filter.paymentMethod } } } : {}), ...((filter.productId || filter.categoryId) ? { items: { some: itemWhere } } : {}) }, select: { id: true, invoiceNumber: true, soldAt: true, paymentStatus: true, totalMinor: true, paidMinor: true, customer: { select: { id: true, name: true, businessName: true } }, payments: { select: { method: true, amountMinor: true } }, items: { where: itemWhere, select: { productId: true, quantityBase: true, lineTotalMinor: true, product: { select: { name: true, sku: true, category: { select: { name: true } } } } } } }, orderBy: { soldAt: "asc" } });
    const daily = new Map<string, { date: string; invoiceCount: number; quantityBase: number; salesMinor: number }>(); const products = new Map<string, { productId: string; name: string; sku: string; category: string | null; invoiceCount: Set<string>; quantityBase: number; salesMinor: number }>(); const customers = new Map<string, { customerId: string | null; name: string; invoiceCount: number; salesMinor: number }>(); const settlements = new Map<string, { type: string; invoiceCount: number; salesMinor: number }>();
    const invoices = sales.map((sale) => { const salesMinor = sale.items.reduce((sum, item) => sum + item.lineTotalMinor, 0); const quantityBase = sale.items.reduce((sum, item) => sum + item.quantityBase, 0); const date = dayKey(sale.soldAt); const d = add(daily, date, () => ({ date, invoiceCount: 0, quantityBase: 0, salesMinor: 0 })); d.invoiceCount++; d.quantityBase += quantityBase; d.salesMinor += salesMinor; const customerKey = sale.customer?.id ?? "WALK_IN"; const c = add(customers, customerKey, () => ({ customerId: sale.customer?.id ?? null, name: sale.customer?.businessName ?? sale.customer?.name ?? "Walk-in customer", invoiceCount: 0, salesMinor: 0 })); c.invoiceCount++; c.salesMinor += salesMinor; const cashPaid = sale.payments.filter((payment) => payment.method === "CASH").reduce((sum, payment) => sum + payment.amountMinor, 0); const settlement = classifySaleSettlement(sale.paymentStatus, sale.totalMinor, cashPaid); const s = add(settlements, settlement, () => ({ type: settlement, invoiceCount: 0, salesMinor: 0 })); s.invoiceCount++; s.salesMinor += salesMinor; for (const item of sale.items) { const p = add(products, item.productId, () => ({ productId: item.productId, name: item.product.name, sku: item.product.sku, category: item.product.category?.name ?? null, invoiceCount: new Set(), quantityBase: 0, salesMinor: 0 })); p.invoiceCount.add(sale.id); p.quantityBase += item.quantityBase; p.salesMinor += item.lineTotalMinor; } return { invoiceNumber: sale.invoiceNumber, date, customer: c.name, settlement, paymentMethods: [...new Set(sale.payments.map((payment) => payment.method))].join(", ") || "CREDIT", quantityBase, sales: minorToMoney(salesMinor), paid: minorToMoney(Math.min(sale.paidMinor, salesMinor)) }; });
    const totalMinor = sales.reduce((sum, sale) => sum + sale.items.reduce((lineSum, item) => lineSum + item.lineTotalMinor, 0), 0); return { summary: { invoices: sales.length, quantityBase: invoices.reduce((sum, row) => sum + row.quantityBase, 0), sales: minorToMoney(totalMinor) }, invoices, daily: [...daily.values()].map(moneyRow), products: [...products.values()].map((row) => ({ ...row, invoiceCount: row.invoiceCount.size, sales: minorToMoney(row.salesMinor) })).sort((a, b) => b.salesMinor - a.salesMinor), customers: [...customers.values()].map(moneyRow).sort((a, b) => b.salesMinor - a.salesMinor), settlements: [...settlements.values()].map(moneyRow) };
  }

  async purchases(filter: ReportDateFilter) {
    const itemWhere: Prisma.PurchaseItemWhereInput = { ...(filter.productId ? { productId: filter.productId } : {}), ...(filter.categoryId ? { product: { categoryId: filter.categoryId } } : {}) }; const purchases = await this.db.purchase.findMany({ where: { status: "POSTED", purchasedAt: range(filter.from, filter.to), ...(filter.supplierId ? { supplierId: filter.supplierId } : {}), ...(filter.paymentStatus ? { paymentStatus: filter.paymentStatus } : {}), ...(filter.paymentMethod ? { payments: { some: { method: filter.paymentMethod } } } : {}), ...((filter.productId || filter.categoryId) ? { items: { some: itemWhere } } : {}) }, select: { id: true, invoiceNumber: true, supplierInvoice: true, purchasedAt: true, paymentStatus: true, totalMinor: true, paidMinor: true, supplier: { select: { id: true, name: true, businessName: true } }, payments: { select: { method: true } }, items: { where: itemWhere, select: { quantityBase: true, lineTotalMinor: true } } }, orderBy: { purchasedAt: "asc" } }); const daily = new Map<string, { date: string; invoiceCount: number; purchasesMinor: number }>(); const suppliers = new Map<string, { supplierId: string; name: string; invoiceCount: number; purchasesMinor: number }>(); const rows = purchases.map((purchase) => { const amountMinor = filter.productId || filter.categoryId ? purchase.items.reduce((sum, item) => sum + item.lineTotalMinor, 0) : purchase.totalMinor; const date = dayKey(purchase.purchasedAt); const d = add(daily, date, () => ({ date, invoiceCount: 0, purchasesMinor: 0 })); d.invoiceCount++; d.purchasesMinor += amountMinor; const s = add(suppliers, purchase.supplier.id, () => ({ supplierId: purchase.supplier.id, name: purchase.supplier.businessName ?? purchase.supplier.name, invoiceCount: 0, purchasesMinor: 0 })); s.invoiceCount++; s.purchasesMinor += amountMinor; return { invoiceNumber: purchase.invoiceNumber, supplierInvoice: purchase.supplierInvoice, date, supplier: s.name, paymentStatus: purchase.paymentStatus, paymentMethods: [...new Set(purchase.payments.map((payment) => payment.method))].join(", ") || "CREDIT", purchases: minorToMoney(amountMinor), paid: minorToMoney(Math.min(purchase.paidMinor, amountMinor)) }; }); const total = purchases.reduce((sum, purchase) => sum + (filter.productId || filter.categoryId ? purchase.items.reduce((value, item) => value + item.lineTotalMinor, 0) : purchase.totalMinor), 0); return { summary: { invoices: rows.length, purchases: minorToMoney(total) }, rows, daily: [...daily.values()].map((row) => ({ ...row, purchases: minorToMoney(row.purchasesMinor) })), suppliers: [...suppliers.values()].map((row) => ({ ...row, purchases: minorToMoney(row.purchasesMinor) })).sort((a, b) => b.purchasesMinor - a.purchasesMinor) };
  }

  async inventory(filter: InventoryReportFilter) { const where: Prisma.ProductWhereInput = { deletedAt: null, isActive: true, ...(filter.productId ? { id: filter.productId } : {}), ...(filter.categoryId ? { categoryId: filter.categoryId } : {}) }; const products = await this.db.product.findMany({ where, select: { id: true, name: true, sku: true, stockOnHandBaseQty: true, reorderLevelBaseQty: true, baseUnit: { select: { symbol: true } }, category: { select: { name: true } }, batches: { where: { stockOnHandBaseQty: { gt: 0 } }, select: { id: true, batchNumber: true, expiryDate: true, stockOnHandBaseQty: true }, orderBy: { expiryDate: "asc" } } }, orderBy: { name: "asc" } }); const today = pakistanDay(dayKey(new Date())).start; const near = new Date(today.getTime() + filter.nearExpiryDays * 86_400_000); const current = products.map((product) => { const expired = product.batches.filter((batch) => batch.expiryDate && batch.expiryDate < today).reduce((sum, batch) => sum + batch.stockOnHandBaseQty, 0); const available = product.stockOnHandBaseQty - expired; return { productId: product.id, name: product.name, sku: product.sku, category: product.category?.name ?? null, baseUnit: product.baseUnit.symbol, currentBaseQty: product.stockOnHandBaseQty, availableBaseQty: available, reorderLevelBaseQty: product.reorderLevelBaseQty, isLowStock: available <= product.reorderLevelBaseQty }; }); const batches = products.flatMap((product) => product.batches.map((batch) => ({ productId: product.id, product: product.name, sku: product.sku, batchNumber: batch.batchNumber, expiryDate: batch.expiryDate?.toISOString().slice(0, 10) ?? null, stockBaseQty: batch.stockOnHandBaseQty, baseUnit: product.baseUnit.symbol, status: batch.expiryDate && batch.expiryDate < today ? "EXPIRED" : batch.expiryDate && batch.expiryDate <= near ? "NEAR_EXPIRY" : "OK" }))); return { current, lowStock: current.filter((row) => row.isLowStock), batches, nearExpiry: batches.filter((row) => row.status === "NEAR_EXPIRY"), expiredBatches: batches.filter((row) => row.status === "EXPIRED") }; }

  async writeOffs(filter: ReportDateFilter) { const rows = await this.db.damageEntry.findMany({ where: { occurredAt: range(filter.from, filter.to), ...(filter.productId ? { productId: filter.productId } : {}), ...(filter.categoryId ? { product: { categoryId: filter.categoryId } } : {}) }, select: { entryNumber: true, type: true, quantityBase: true, reason: true, occurredAt: true, product: { select: { name: true, sku: true, baseUnit: { select: { symbol: true } } } }, batch: { select: { batchNumber: true, expiryDate: true } }, createdBy: { select: { displayName: true } } }, orderBy: { occurredAt: "desc" } }); return { rows: rows.map((row) => ({ ...row, date: dayKey(row.occurredAt) })), summary: { damagedBaseQty: rows.filter((row) => row.type === "DAMAGED").reduce((sum, row) => sum + row.quantityBase, 0), expiredBaseQty: rows.filter((row) => row.type === "EXPIRED").reduce((sum, row) => sum + row.quantityBase, 0) } };
  }

  async customerLedgers(filter: LedgerReportFilter) { const to = pakistanDay(filter.to).end; const from = pakistanDay(filter.from).start; const entries = await this.db.customerLedger.findMany({ where: { ...(filter.customerId ? { customerId: filter.customerId } : {}), occurredAt: { lte: to } }, select: { id: true, customerId: true, entryType: true, debitMinor: true, creditMinor: true, sourceType: true, sourceId: true, notes: true, dueDate: true, occurredAt: true, customer: { select: { id: true, code: true, name: true, businessName: true } } }, orderBy: { occurredAt: "asc" } }); const grouped = new Map<string, { partyId: string; code: string; name: string; debitMinor: number; creditMinor: number; periodDebitMinor: number; periodCreditMinor: number }>(); for (const entry of entries) { const p = entry.customer; const row = add(grouped, p.id, () => ({ partyId: p.id, code: p.code, name: p.businessName ?? p.name, debitMinor: 0, creditMinor: 0, periodDebitMinor: 0, periodCreditMinor: 0 })); row.debitMinor += entry.debitMinor; row.creditMinor += entry.creditMinor; if (entry.occurredAt >= from) { row.periodDebitMinor += entry.debitMinor; row.periodCreditMinor += entry.creditMinor; } } return { parties: [...grouped.values()].map((row) => ({ ...row, periodDebit: minorToMoney(row.periodDebitMinor), periodCredit: minorToMoney(row.periodCreditMinor), balance: minorToMoney(row.debitMinor - row.creditMinor) })).filter((row) => row.debitMinor !== row.creditMinor || row.periodDebitMinor || row.periodCreditMinor), entries: entries.filter((entry) => entry.occurredAt >= from).map((entry) => ({ ...entry, party: entry.customer, date: dayKey(entry.occurredAt), debit: minorToMoney(entry.debitMinor), credit: minorToMoney(entry.creditMinor) })) };
  }

  async supplierLedgerReport(filter: LedgerReportFilter) { const to = pakistanDay(filter.to).end; const from = pakistanDay(filter.from).start; const entries = await this.db.supplierLedger.findMany({ where: { ...(filter.supplierId ? { supplierId: filter.supplierId } : {}), occurredAt: { lte: to } }, select: { id: true, entryType: true, debitMinor: true, creditMinor: true, notes: true, occurredAt: true, supplier: { select: { id: true, code: true, name: true, businessName: true } } }, orderBy: { occurredAt: "asc" } }); const grouped = new Map<string, { partyId: string; code: string; name: string; debitMinor: number; creditMinor: number; periodDebitMinor: number; periodCreditMinor: number }>(); for (const entry of entries) { const p = entry.supplier; const row = add(grouped, p.id, () => ({ partyId: p.id, code: p.code, name: p.businessName ?? p.name, debitMinor: 0, creditMinor: 0, periodDebitMinor: 0, periodCreditMinor: 0 })); row.debitMinor += entry.debitMinor; row.creditMinor += entry.creditMinor; if (entry.occurredAt >= from) { row.periodDebitMinor += entry.debitMinor; row.periodCreditMinor += entry.creditMinor; } } return { parties: [...grouped.values()].map((row) => ({ ...row, periodDebit: minorToMoney(row.periodDebitMinor), periodCredit: minorToMoney(row.periodCreditMinor), balance: minorToMoney(row.creditMinor - row.debitMinor) })), entries: entries.filter((entry) => entry.occurredAt >= from).map((entry) => ({ ...entry, party: entry.supplier, date: dayKey(entry.occurredAt), debit: minorToMoney(entry.debitMinor), credit: minorToMoney(entry.creditMinor) })) };
  }

  async expenses(filter: ReportDateFilter) { const rows = await this.db.expense.findMany({ where: { incurredAt: range(filter.from, filter.to), status: "POSTED", ...(filter.paymentMethod ? { method: filter.paymentMethod } : {}) }, select: { voucherNumber: true, category: true, description: true, amountMinor: true, method: true, incurredAt: true, createdBy: { select: { displayName: true } } }, orderBy: { incurredAt: "desc" } }); const categories = new Map<string, number>(); rows.forEach((row) => categories.set(row.category, (categories.get(row.category) ?? 0) + row.amountMinor)); return { rows: rows.map((row) => ({ ...row, date: dayKey(row.incurredAt), amount: minorToMoney(row.amountMinor) })), categories: [...categories].map(([category, amountMinor]) => ({ category, amount: minorToMoney(amountMinor) })), total: minorToMoney(rows.reduce((sum, row) => sum + row.amountMinor, 0)) };
  }
}

function moneyRow<T extends Record<string, unknown>>(row: T) { const result: Record<string, unknown> = { ...row }; for (const [key, value] of Object.entries(row)) if (key.endsWith("Minor") && typeof value === "number") result[key.slice(0, -5)] = minorToMoney(value); return result as T & Record<string, unknown>; }
